/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/msg/contacts_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/ContactsState", ContactsStateTypeSupport)
}

// Do not create instances of this type directly. Always use NewContactsState
// function instead.
type ContactsState struct {
	Header std_msgs_msg.Header `yaml:"header"`// stamp
	States []ContactState `yaml:"states"`// array of geom pairs in contact
}

// NewContactsState creates a new ContactsState with default values.
func NewContactsState() *ContactsState {
	self := ContactsState{}
	self.SetDefaults()
	return &self
}

func (t *ContactsState) Clone() *ContactsState {
	c := &ContactsState{}
	c.Header = *t.Header.Clone()
	if t.States != nil {
		c.States = make([]ContactState, len(t.States))
		CloneContactStateSlice(c.States, t.States)
	}
	return c
}

func (t *ContactsState) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ContactsState) SetDefaults() {
	t.Header.SetDefaults()
	t.States = nil
}

// CloneContactsStateSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneContactsStateSlice(dst, src []ContactsState) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ContactsStateTypeSupport types.MessageTypeSupport = _ContactsStateTypeSupport{}

type _ContactsStateTypeSupport struct{}

func (t _ContactsStateTypeSupport) New() types.Message {
	return NewContactsState()
}

func (t _ContactsStateTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__msg__ContactsState
	return (unsafe.Pointer)(C.gazebo_msgs__msg__ContactsState__create())
}

func (t _ContactsStateTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__msg__ContactsState__destroy((*C.gazebo_msgs__msg__ContactsState)(pointer_to_free))
}

func (t _ContactsStateTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ContactsState)
	mem := (*C.gazebo_msgs__msg__ContactsState)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	ContactState__Sequence_to_C(&mem.states, m.States)
}

func (t _ContactsStateTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ContactsState)
	mem := (*C.gazebo_msgs__msg__ContactsState)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	ContactState__Sequence_to_Go(&m.States, mem.states)
}

func (t _ContactsStateTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__msg__ContactsState())
}

type CContactsState = C.gazebo_msgs__msg__ContactsState
type CContactsState__Sequence = C.gazebo_msgs__msg__ContactsState__Sequence

func ContactsState__Sequence_to_Go(goSlice *[]ContactsState, cSlice CContactsState__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ContactsState, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__msg__ContactsState__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__msg__ContactsState * uintptr(i)),
		))
		ContactsStateTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ContactsState__Sequence_to_C(cSlice *CContactsState__Sequence, goSlice []ContactsState) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__msg__ContactsState)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__msg__ContactsState * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__msg__ContactsState)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__msg__ContactsState * uintptr(i)),
		))
		ContactsStateTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ContactsState__Array_to_Go(goSlice []ContactsState, cSlice []CContactsState) {
	for i := 0; i < len(cSlice); i++ {
		ContactsStateTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ContactsState__Array_to_C(cSlice []CContactsState, goSlice []ContactsState) {
	for i := 0; i < len(goSlice); i++ {
		ContactsStateTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
