/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/geometry_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/msg/model_states.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/ModelStates", ModelStatesTypeSupport)
}

// Do not create instances of this type directly. Always use NewModelStates
// function instead.
type ModelStates struct {
	Name []string `yaml:"name"`// model names. broadcast all model states in world frame
	Pose []geometry_msgs_msg.Pose `yaml:"pose"`// desired pose in world frame. broadcast all model states in world frame
	Twist []geometry_msgs_msg.Twist `yaml:"twist"`// desired twist in world frame. broadcast all model states in world frame
}

// NewModelStates creates a new ModelStates with default values.
func NewModelStates() *ModelStates {
	self := ModelStates{}
	self.SetDefaults()
	return &self
}

func (t *ModelStates) Clone() *ModelStates {
	c := &ModelStates{}
	if t.Name != nil {
		c.Name = make([]string, len(t.Name))
		copy(c.Name, t.Name)
	}
	if t.Pose != nil {
		c.Pose = make([]geometry_msgs_msg.Pose, len(t.Pose))
		geometry_msgs_msg.ClonePoseSlice(c.Pose, t.Pose)
	}
	if t.Twist != nil {
		c.Twist = make([]geometry_msgs_msg.Twist, len(t.Twist))
		geometry_msgs_msg.CloneTwistSlice(c.Twist, t.Twist)
	}
	return c
}

func (t *ModelStates) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ModelStates) SetDefaults() {
	t.Name = nil
	t.Pose = nil
	t.Twist = nil
}

// CloneModelStatesSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneModelStatesSlice(dst, src []ModelStates) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ModelStatesTypeSupport types.MessageTypeSupport = _ModelStatesTypeSupport{}

type _ModelStatesTypeSupport struct{}

func (t _ModelStatesTypeSupport) New() types.Message {
	return NewModelStates()
}

func (t _ModelStatesTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__msg__ModelStates
	return (unsafe.Pointer)(C.gazebo_msgs__msg__ModelStates__create())
}

func (t _ModelStatesTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__msg__ModelStates__destroy((*C.gazebo_msgs__msg__ModelStates)(pointer_to_free))
}

func (t _ModelStatesTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ModelStates)
	mem := (*C.gazebo_msgs__msg__ModelStates)(dst)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.name)), m.Name)
	geometry_msgs_msg.Pose__Sequence_to_C((*geometry_msgs_msg.CPose__Sequence)(unsafe.Pointer(&mem.pose)), m.Pose)
	geometry_msgs_msg.Twist__Sequence_to_C((*geometry_msgs_msg.CTwist__Sequence)(unsafe.Pointer(&mem.twist)), m.Twist)
}

func (t _ModelStatesTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ModelStates)
	mem := (*C.gazebo_msgs__msg__ModelStates)(ros2_message_buffer)
	primitives.String__Sequence_to_Go(&m.Name, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.name)))
	geometry_msgs_msg.Pose__Sequence_to_Go(&m.Pose, *(*geometry_msgs_msg.CPose__Sequence)(unsafe.Pointer(&mem.pose)))
	geometry_msgs_msg.Twist__Sequence_to_Go(&m.Twist, *(*geometry_msgs_msg.CTwist__Sequence)(unsafe.Pointer(&mem.twist)))
}

func (t _ModelStatesTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__msg__ModelStates())
}

type CModelStates = C.gazebo_msgs__msg__ModelStates
type CModelStates__Sequence = C.gazebo_msgs__msg__ModelStates__Sequence

func ModelStates__Sequence_to_Go(goSlice *[]ModelStates, cSlice CModelStates__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ModelStates, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__msg__ModelStates__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__msg__ModelStates * uintptr(i)),
		))
		ModelStatesTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ModelStates__Sequence_to_C(cSlice *CModelStates__Sequence, goSlice []ModelStates) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__msg__ModelStates)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__msg__ModelStates * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__msg__ModelStates)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__msg__ModelStates * uintptr(i)),
		))
		ModelStatesTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ModelStates__Array_to_Go(goSlice []ModelStates, cSlice []CModelStates) {
	for i := 0; i < len(cSlice); i++ {
		ModelStatesTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ModelStates__Array_to_C(cSlice []CModelStates, goSlice []ModelStates) {
	for i := 0; i < len(goSlice); i++ {
		ModelStatesTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
