/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/is_paused.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/IsPaused_Request", IsPaused_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewIsPaused_Request
// function instead.
type IsPaused_Request struct {
}

// NewIsPaused_Request creates a new IsPaused_Request with default values.
func NewIsPaused_Request() *IsPaused_Request {
	self := IsPaused_Request{}
	self.SetDefaults()
	return &self
}

func (t *IsPaused_Request) Clone() *IsPaused_Request {
	c := &IsPaused_Request{}
	return c
}

func (t *IsPaused_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsPaused_Request) SetDefaults() {
}

// CloneIsPaused_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsPaused_RequestSlice(dst, src []IsPaused_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsPaused_RequestTypeSupport types.MessageTypeSupport = _IsPaused_RequestTypeSupport{}

type _IsPaused_RequestTypeSupport struct{}

func (t _IsPaused_RequestTypeSupport) New() types.Message {
	return NewIsPaused_Request()
}

func (t _IsPaused_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__IsPaused_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__IsPaused_Request__create())
}

func (t _IsPaused_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__IsPaused_Request__destroy((*C.rosbag2_interfaces__srv__IsPaused_Request)(pointer_to_free))
}

func (t _IsPaused_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _IsPaused_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _IsPaused_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__IsPaused_Request())
}

type CIsPaused_Request = C.rosbag2_interfaces__srv__IsPaused_Request
type CIsPaused_Request__Sequence = C.rosbag2_interfaces__srv__IsPaused_Request__Sequence

func IsPaused_Request__Sequence_to_Go(goSlice *[]IsPaused_Request, cSlice CIsPaused_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsPaused_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__IsPaused_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Request * uintptr(i)),
		))
		IsPaused_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func IsPaused_Request__Sequence_to_C(cSlice *CIsPaused_Request__Sequence, goSlice []IsPaused_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__IsPaused_Request)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__IsPaused_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Request * uintptr(i)),
		))
		IsPaused_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func IsPaused_Request__Array_to_Go(goSlice []IsPaused_Request, cSlice []CIsPaused_Request) {
	for i := 0; i < len(cSlice); i++ {
		IsPaused_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsPaused_Request__Array_to_C(cSlice []CIsPaused_Request, goSlice []IsPaused_Request) {
	for i := 0; i < len(goSlice); i++ {
		IsPaused_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
