/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/is_paused.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/IsPaused_Response", IsPaused_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewIsPaused_Response
// function instead.
type IsPaused_Response struct {
	Paused bool `yaml:"paused"`
}

// NewIsPaused_Response creates a new IsPaused_Response with default values.
func NewIsPaused_Response() *IsPaused_Response {
	self := IsPaused_Response{}
	self.SetDefaults()
	return &self
}

func (t *IsPaused_Response) Clone() *IsPaused_Response {
	c := &IsPaused_Response{}
	c.Paused = t.Paused
	return c
}

func (t *IsPaused_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *IsPaused_Response) SetDefaults() {
	t.Paused = false
}

// CloneIsPaused_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneIsPaused_ResponseSlice(dst, src []IsPaused_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var IsPaused_ResponseTypeSupport types.MessageTypeSupport = _IsPaused_ResponseTypeSupport{}

type _IsPaused_ResponseTypeSupport struct{}

func (t _IsPaused_ResponseTypeSupport) New() types.Message {
	return NewIsPaused_Response()
}

func (t _IsPaused_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__IsPaused_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__IsPaused_Response__create())
}

func (t _IsPaused_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__IsPaused_Response__destroy((*C.rosbag2_interfaces__srv__IsPaused_Response)(pointer_to_free))
}

func (t _IsPaused_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*IsPaused_Response)
	mem := (*C.rosbag2_interfaces__srv__IsPaused_Response)(dst)
	mem.paused = C.bool(m.Paused)
}

func (t _IsPaused_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*IsPaused_Response)
	mem := (*C.rosbag2_interfaces__srv__IsPaused_Response)(ros2_message_buffer)
	m.Paused = bool(mem.paused)
}

func (t _IsPaused_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__IsPaused_Response())
}

type CIsPaused_Response = C.rosbag2_interfaces__srv__IsPaused_Response
type CIsPaused_Response__Sequence = C.rosbag2_interfaces__srv__IsPaused_Response__Sequence

func IsPaused_Response__Sequence_to_Go(goSlice *[]IsPaused_Response, cSlice CIsPaused_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]IsPaused_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__IsPaused_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Response * uintptr(i)),
		))
		IsPaused_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func IsPaused_Response__Sequence_to_C(cSlice *CIsPaused_Response__Sequence, goSlice []IsPaused_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__IsPaused_Response)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__IsPaused_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__IsPaused_Response * uintptr(i)),
		))
		IsPaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func IsPaused_Response__Array_to_Go(goSlice []IsPaused_Response, cSlice []CIsPaused_Response) {
	for i := 0; i < len(cSlice); i++ {
		IsPaused_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func IsPaused_Response__Array_to_C(cSlice []CIsPaused_Response, goSlice []IsPaused_Response) {
	for i := 0; i < len(goSlice); i++ {
		IsPaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
