/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/pause.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Pause_Request", Pause_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewPause_Request
// function instead.
type Pause_Request struct {
}

// NewPause_Request creates a new Pause_Request with default values.
func NewPause_Request() *Pause_Request {
	self := Pause_Request{}
	self.SetDefaults()
	return &self
}

func (t *Pause_Request) Clone() *Pause_Request {
	c := &Pause_Request{}
	return c
}

func (t *Pause_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Pause_Request) SetDefaults() {
}

// ClonePause_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePause_RequestSlice(dst, src []Pause_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Pause_RequestTypeSupport types.MessageTypeSupport = _Pause_RequestTypeSupport{}

type _Pause_RequestTypeSupport struct{}

func (t _Pause_RequestTypeSupport) New() types.Message {
	return NewPause_Request()
}

func (t _Pause_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Pause_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Pause_Request__create())
}

func (t _Pause_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Pause_Request__destroy((*C.rosbag2_interfaces__srv__Pause_Request)(pointer_to_free))
}

func (t _Pause_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Pause_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Pause_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Pause_Request())
}

type CPause_Request = C.rosbag2_interfaces__srv__Pause_Request
type CPause_Request__Sequence = C.rosbag2_interfaces__srv__Pause_Request__Sequence

func Pause_Request__Sequence_to_Go(goSlice *[]Pause_Request, cSlice CPause_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Pause_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__Pause_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Pause_Request * uintptr(i)),
		))
		Pause_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Pause_Request__Sequence_to_C(cSlice *CPause_Request__Sequence, goSlice []Pause_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Pause_Request)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__Pause_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__Pause_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Pause_Request * uintptr(i)),
		))
		Pause_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Pause_Request__Array_to_Go(goSlice []Pause_Request, cSlice []CPause_Request) {
	for i := 0; i < len(cSlice); i++ {
		Pause_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Pause_Request__Array_to_C(cSlice []CPause_Request, goSlice []Pause_Request) {
	for i := 0; i < len(goSlice); i++ {
		Pause_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
