/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/pause.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Pause_Response", Pause_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewPause_Response
// function instead.
type Pause_Response struct {
}

// NewPause_Response creates a new Pause_Response with default values.
func NewPause_Response() *Pause_Response {
	self := Pause_Response{}
	self.SetDefaults()
	return &self
}

func (t *Pause_Response) Clone() *Pause_Response {
	c := &Pause_Response{}
	return c
}

func (t *Pause_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Pause_Response) SetDefaults() {
}

// ClonePause_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func ClonePause_ResponseSlice(dst, src []Pause_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Pause_ResponseTypeSupport types.MessageTypeSupport = _Pause_ResponseTypeSupport{}

type _Pause_ResponseTypeSupport struct{}

func (t _Pause_ResponseTypeSupport) New() types.Message {
	return NewPause_Response()
}

func (t _Pause_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Pause_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Pause_Response__create())
}

func (t _Pause_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Pause_Response__destroy((*C.rosbag2_interfaces__srv__Pause_Response)(pointer_to_free))
}

func (t _Pause_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Pause_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Pause_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Pause_Response())
}

type CPause_Response = C.rosbag2_interfaces__srv__Pause_Response
type CPause_Response__Sequence = C.rosbag2_interfaces__srv__Pause_Response__Sequence

func Pause_Response__Sequence_to_Go(goSlice *[]Pause_Response, cSlice CPause_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Pause_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__Pause_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Pause_Response * uintptr(i)),
		))
		Pause_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Pause_Response__Sequence_to_C(cSlice *CPause_Response__Sequence, goSlice []Pause_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Pause_Response)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__Pause_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__Pause_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Pause_Response * uintptr(i)),
		))
		Pause_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Pause_Response__Array_to_Go(goSlice []Pause_Response, cSlice []CPause_Response) {
	for i := 0; i < len(cSlice); i++ {
		Pause_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Pause_Response__Array_to_C(cSlice []CPause_Response, goSlice []Pause_Response) {
	for i := 0; i < len(goSlice); i++ {
		Pause_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
