/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/resume.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Resume_Response", Resume_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewResume_Response
// function instead.
type Resume_Response struct {
}

// NewResume_Response creates a new Resume_Response with default values.
func NewResume_Response() *Resume_Response {
	self := Resume_Response{}
	self.SetDefaults()
	return &self
}

func (t *Resume_Response) Clone() *Resume_Response {
	c := &Resume_Response{}
	return c
}

func (t *Resume_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Resume_Response) SetDefaults() {
}

// CloneResume_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneResume_ResponseSlice(dst, src []Resume_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Resume_ResponseTypeSupport types.MessageTypeSupport = _Resume_ResponseTypeSupport{}

type _Resume_ResponseTypeSupport struct{}

func (t _Resume_ResponseTypeSupport) New() types.Message {
	return NewResume_Response()
}

func (t _Resume_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Resume_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Resume_Response__create())
}

func (t _Resume_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Resume_Response__destroy((*C.rosbag2_interfaces__srv__Resume_Response)(pointer_to_free))
}

func (t _Resume_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _Resume_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _Resume_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Resume_Response())
}

type CResume_Response = C.rosbag2_interfaces__srv__Resume_Response
type CResume_Response__Sequence = C.rosbag2_interfaces__srv__Resume_Response__Sequence

func Resume_Response__Sequence_to_Go(goSlice *[]Resume_Response, cSlice CResume_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Resume_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__Resume_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Resume_Response * uintptr(i)),
		))
		Resume_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Resume_Response__Sequence_to_C(cSlice *CResume_Response__Sequence, goSlice []Resume_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Resume_Response)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__Resume_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__Resume_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Resume_Response * uintptr(i)),
		))
		Resume_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Resume_Response__Array_to_Go(goSlice []Resume_Response, cSlice []CResume_Response) {
	for i := 0; i < len(cSlice); i++ {
		Resume_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Resume_Response__Array_to_C(cSlice []CResume_Response, goSlice []Resume_Response) {
	for i := 0; i < len(goSlice); i++ {
		Resume_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
