/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "github.com/mehmetkillioglu/rclgo-msgs/builtin_interfaces/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c
#cgo LDFLAGS: -lbuiltin_interfaces__rosidl_typesupport_c -lbuiltin_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/seek.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/Seek_Request", Seek_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSeek_Request
// function instead.
type Seek_Request struct {
	Time builtin_interfaces_msg.Time `yaml:"time"`
}

// NewSeek_Request creates a new Seek_Request with default values.
func NewSeek_Request() *Seek_Request {
	self := Seek_Request{}
	self.SetDefaults()
	return &self
}

func (t *Seek_Request) Clone() *Seek_Request {
	c := &Seek_Request{}
	c.Time = *t.Time.Clone()
	return c
}

func (t *Seek_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *Seek_Request) SetDefaults() {
	t.Time.SetDefaults()
}

// CloneSeek_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSeek_RequestSlice(dst, src []Seek_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var Seek_RequestTypeSupport types.MessageTypeSupport = _Seek_RequestTypeSupport{}

type _Seek_RequestTypeSupport struct{}

func (t _Seek_RequestTypeSupport) New() types.Message {
	return NewSeek_Request()
}

func (t _Seek_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__Seek_Request
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__Seek_Request__create())
}

func (t _Seek_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__Seek_Request__destroy((*C.rosbag2_interfaces__srv__Seek_Request)(pointer_to_free))
}

func (t _Seek_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*Seek_Request)
	mem := (*C.rosbag2_interfaces__srv__Seek_Request)(dst)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.time), &m.Time)
}

func (t _Seek_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*Seek_Request)
	mem := (*C.rosbag2_interfaces__srv__Seek_Request)(ros2_message_buffer)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.Time, unsafe.Pointer(&mem.time))
}

func (t _Seek_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__Seek_Request())
}

type CSeek_Request = C.rosbag2_interfaces__srv__Seek_Request
type CSeek_Request__Sequence = C.rosbag2_interfaces__srv__Seek_Request__Sequence

func Seek_Request__Sequence_to_Go(goSlice *[]Seek_Request, cSlice CSeek_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]Seek_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__Seek_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Seek_Request * uintptr(i)),
		))
		Seek_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func Seek_Request__Sequence_to_C(cSlice *CSeek_Request__Sequence, goSlice []Seek_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__Seek_Request)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__Seek_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__Seek_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__Seek_Request * uintptr(i)),
		))
		Seek_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func Seek_Request__Array_to_Go(goSlice []Seek_Request, cSlice []CSeek_Request) {
	for i := 0; i < len(cSlice); i++ {
		Seek_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func Seek_Request__Array_to_C(cSlice []CSeek_Request, goSlice []Seek_Request) {
	for i := 0; i < len(goSlice); i++ {
		Seek_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
