/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package rosbag2_interfaces_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lrosbag2_interfaces__rosidl_typesupport_c -lrosbag2_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <rosbag2_interfaces/srv/toggle_paused.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("rosbag2_interfaces/TogglePaused_Response", TogglePaused_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewTogglePaused_Response
// function instead.
type TogglePaused_Response struct {
}

// NewTogglePaused_Response creates a new TogglePaused_Response with default values.
func NewTogglePaused_Response() *TogglePaused_Response {
	self := TogglePaused_Response{}
	self.SetDefaults()
	return &self
}

func (t *TogglePaused_Response) Clone() *TogglePaused_Response {
	c := &TogglePaused_Response{}
	return c
}

func (t *TogglePaused_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *TogglePaused_Response) SetDefaults() {
}

// CloneTogglePaused_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneTogglePaused_ResponseSlice(dst, src []TogglePaused_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var TogglePaused_ResponseTypeSupport types.MessageTypeSupport = _TogglePaused_ResponseTypeSupport{}

type _TogglePaused_ResponseTypeSupport struct{}

func (t _TogglePaused_ResponseTypeSupport) New() types.Message {
	return NewTogglePaused_Response()
}

func (t _TogglePaused_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.rosbag2_interfaces__srv__TogglePaused_Response
	return (unsafe.Pointer)(C.rosbag2_interfaces__srv__TogglePaused_Response__create())
}

func (t _TogglePaused_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.rosbag2_interfaces__srv__TogglePaused_Response__destroy((*C.rosbag2_interfaces__srv__TogglePaused_Response)(pointer_to_free))
}

func (t _TogglePaused_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _TogglePaused_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _TogglePaused_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__rosbag2_interfaces__srv__TogglePaused_Response())
}

type CTogglePaused_Response = C.rosbag2_interfaces__srv__TogglePaused_Response
type CTogglePaused_Response__Sequence = C.rosbag2_interfaces__srv__TogglePaused_Response__Sequence

func TogglePaused_Response__Sequence_to_Go(goSlice *[]TogglePaused_Response, cSlice CTogglePaused_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]TogglePaused_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.rosbag2_interfaces__srv__TogglePaused_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__TogglePaused_Response * uintptr(i)),
		))
		TogglePaused_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func TogglePaused_Response__Sequence_to_C(cSlice *CTogglePaused_Response__Sequence, goSlice []TogglePaused_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.rosbag2_interfaces__srv__TogglePaused_Response)(C.malloc((C.size_t)(C.sizeof_struct_rosbag2_interfaces__srv__TogglePaused_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.rosbag2_interfaces__srv__TogglePaused_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_rosbag2_interfaces__srv__TogglePaused_Response * uintptr(i)),
		))
		TogglePaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func TogglePaused_Response__Array_to_Go(goSlice []TogglePaused_Response, cSlice []CTogglePaused_Response) {
	for i := 0; i < len(cSlice); i++ {
		TogglePaused_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func TogglePaused_Response__Array_to_C(cSlice []CTogglePaused_Response, goSlice []TogglePaused_Response) {
	for i := 0; i < len(goSlice); i++ {
		TogglePaused_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
