/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_pose_stamped.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GeoPoseStamped", GeoPoseStampedTypeSupport)
}

// Do not create instances of this type directly. Always use NewGeoPoseStamped
// function instead.
type GeoPoseStamped struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Pose GeoPose `yaml:"pose"`
}

// NewGeoPoseStamped creates a new GeoPoseStamped with default values.
func NewGeoPoseStamped() *GeoPoseStamped {
	self := GeoPoseStamped{}
	self.SetDefaults()
	return &self
}

func (t *GeoPoseStamped) Clone() *GeoPoseStamped {
	c := &GeoPoseStamped{}
	c.Header = *t.Header.Clone()
	c.Pose = *t.Pose.Clone()
	return c
}

func (t *GeoPoseStamped) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GeoPoseStamped) SetDefaults() {
	t.Header.SetDefaults()
	t.Pose.SetDefaults()
}

// CloneGeoPoseStampedSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPoseStampedSlice(dst, src []GeoPoseStamped) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPoseStampedTypeSupport types.MessageTypeSupport = _GeoPoseStampedTypeSupport{}

type _GeoPoseStampedTypeSupport struct{}

func (t _GeoPoseStampedTypeSupport) New() types.Message {
	return NewGeoPoseStamped()
}

func (t _GeoPoseStampedTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPoseStamped
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPoseStamped__create())
}

func (t _GeoPoseStampedTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPoseStamped__destroy((*C.geographic_msgs__msg__GeoPoseStamped)(pointer_to_free))
}

func (t _GeoPoseStampedTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GeoPoseStamped)
	mem := (*C.geographic_msgs__msg__GeoPoseStamped)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	GeoPoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.pose), &m.Pose)
}

func (t _GeoPoseStampedTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPoseStamped)
	mem := (*C.geographic_msgs__msg__GeoPoseStamped)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	GeoPoseTypeSupport.AsGoStruct(&m.Pose, unsafe.Pointer(&mem.pose))
}

func (t _GeoPoseStampedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPoseStamped())
}

type CGeoPoseStamped = C.geographic_msgs__msg__GeoPoseStamped
type CGeoPoseStamped__Sequence = C.geographic_msgs__msg__GeoPoseStamped__Sequence

func GeoPoseStamped__Sequence_to_Go(goSlice *[]GeoPoseStamped, cSlice CGeoPoseStamped__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPoseStamped, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__msg__GeoPoseStamped__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPoseStamped * uintptr(i)),
		))
		GeoPoseStampedTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GeoPoseStamped__Sequence_to_C(cSlice *CGeoPoseStamped__Sequence, goSlice []GeoPoseStamped) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPoseStamped)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__msg__GeoPoseStamped * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__msg__GeoPoseStamped)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPoseStamped * uintptr(i)),
		))
		GeoPoseStampedTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GeoPoseStamped__Array_to_Go(goSlice []GeoPoseStamped, cSlice []CGeoPoseStamped) {
	for i := 0; i < len(cSlice); i++ {
		GeoPoseStampedTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GeoPoseStamped__Array_to_C(cSlice []CGeoPoseStamped, goSlice []GeoPoseStamped) {
	for i := 0; i < len(goSlice); i++ {
		GeoPoseStampedTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
