/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "github.com/tiiuae/rclgo-msgs/geometry_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GeoPose", GeoPoseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGeoPose
// function instead.
type GeoPose struct {
	Position GeoPoint `yaml:"position"`
	Orientation geometry_msgs_msg.Quaternion `yaml:"orientation"`
}

// NewGeoPose creates a new GeoPose with default values.
func NewGeoPose() *GeoPose {
	self := GeoPose{}
	self.SetDefaults()
	return &self
}

func (t *GeoPose) Clone() *GeoPose {
	c := &GeoPose{}
	c.Position = *t.Position.Clone()
	c.Orientation = *t.Orientation.Clone()
	return c
}

func (t *GeoPose) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GeoPose) SetDefaults() {
	t.Position.SetDefaults()
	t.Orientation.SetDefaults()
}

// CloneGeoPoseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPoseSlice(dst, src []GeoPose) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPoseTypeSupport types.MessageTypeSupport = _GeoPoseTypeSupport{}

type _GeoPoseTypeSupport struct{}

func (t _GeoPoseTypeSupport) New() types.Message {
	return NewGeoPose()
}

func (t _GeoPoseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPose
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPose__create())
}

func (t _GeoPoseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPose__destroy((*C.geographic_msgs__msg__GeoPose)(pointer_to_free))
}

func (t _GeoPoseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GeoPose)
	mem := (*C.geographic_msgs__msg__GeoPose)(dst)
	GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.position), &m.Position)
	geometry_msgs_msg.QuaternionTypeSupport.AsCStruct(unsafe.Pointer(&mem.orientation), &m.Orientation)
}

func (t _GeoPoseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPose)
	mem := (*C.geographic_msgs__msg__GeoPose)(ros2_message_buffer)
	GeoPointTypeSupport.AsGoStruct(&m.Position, unsafe.Pointer(&mem.position))
	geometry_msgs_msg.QuaternionTypeSupport.AsGoStruct(&m.Orientation, unsafe.Pointer(&mem.orientation))
}

func (t _GeoPoseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPose())
}

type CGeoPose = C.geographic_msgs__msg__GeoPose
type CGeoPose__Sequence = C.geographic_msgs__msg__GeoPose__Sequence

func GeoPose__Sequence_to_Go(goSlice *[]GeoPose, cSlice CGeoPose__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPose, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__msg__GeoPose__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPose * uintptr(i)),
		))
		GeoPoseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GeoPose__Sequence_to_C(cSlice *CGeoPose__Sequence, goSlice []GeoPose) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPose)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__msg__GeoPose * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__msg__GeoPose)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPose * uintptr(i)),
		))
		GeoPoseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GeoPose__Array_to_Go(goSlice []GeoPose, cSlice []CGeoPose) {
	for i := 0; i < len(cSlice); i++ {
		GeoPoseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GeoPose__Array_to_C(cSlice []CGeoPose, goSlice []GeoPose) {
	for i := 0; i < len(goSlice); i++ {
		GeoPoseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
