/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_point_stamped.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GeoPointStamped", GeoPointStampedTypeSupport)
}

// Do not create instances of this type directly. Always use NewGeoPointStamped
// function instead.
type GeoPointStamped struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Position GeoPoint `yaml:"position"`
}

// NewGeoPointStamped creates a new GeoPointStamped with default values.
func NewGeoPointStamped() *GeoPointStamped {
	self := GeoPointStamped{}
	self.SetDefaults()
	return &self
}

func (t *GeoPointStamped) Clone() *GeoPointStamped {
	c := &GeoPointStamped{}
	c.Header = *t.Header.Clone()
	c.Position = *t.Position.Clone()
	return c
}

func (t *GeoPointStamped) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GeoPointStamped) SetDefaults() {
	t.Header.SetDefaults()
	t.Position.SetDefaults()
}

// CloneGeoPointStampedSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPointStampedSlice(dst, src []GeoPointStamped) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPointStampedTypeSupport types.MessageTypeSupport = _GeoPointStampedTypeSupport{}

type _GeoPointStampedTypeSupport struct{}

func (t _GeoPointStampedTypeSupport) New() types.Message {
	return NewGeoPointStamped()
}

func (t _GeoPointStampedTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPointStamped
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPointStamped__create())
}

func (t _GeoPointStampedTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPointStamped__destroy((*C.geographic_msgs__msg__GeoPointStamped)(pointer_to_free))
}

func (t _GeoPointStampedTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GeoPointStamped)
	mem := (*C.geographic_msgs__msg__GeoPointStamped)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	GeoPointTypeSupport.AsCStruct(unsafe.Pointer(&mem.position), &m.Position)
}

func (t _GeoPointStampedTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPointStamped)
	mem := (*C.geographic_msgs__msg__GeoPointStamped)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	GeoPointTypeSupport.AsGoStruct(&m.Position, unsafe.Pointer(&mem.position))
}

func (t _GeoPointStampedTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPointStamped())
}

type CGeoPointStamped = C.geographic_msgs__msg__GeoPointStamped
type CGeoPointStamped__Sequence = C.geographic_msgs__msg__GeoPointStamped__Sequence

func GeoPointStamped__Sequence_to_Go(goSlice *[]GeoPointStamped, cSlice CGeoPointStamped__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPointStamped, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__msg__GeoPointStamped__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPointStamped * uintptr(i)),
		))
		GeoPointStampedTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GeoPointStamped__Sequence_to_C(cSlice *CGeoPointStamped__Sequence, goSlice []GeoPointStamped) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPointStamped)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__msg__GeoPointStamped * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__msg__GeoPointStamped)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPointStamped * uintptr(i)),
		))
		GeoPointStampedTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GeoPointStamped__Array_to_Go(goSlice []GeoPointStamped, cSlice []CGeoPointStamped) {
	for i := 0; i < len(cSlice); i++ {
		GeoPointStampedTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GeoPointStamped__Array_to_C(cSlice []CGeoPointStamped, goSlice []GeoPointStamped) {
	for i := 0; i < len(goSlice); i++ {
		GeoPointStampedTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
