/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/tiiuae/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/geo_path.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GeoPath", GeoPathTypeSupport)
}

// Do not create instances of this type directly. Always use NewGeoPath
// function instead.
type GeoPath struct {
	Header std_msgs_msg.Header `yaml:"header"`
	Poses []GeoPoseStamped `yaml:"poses"`
}

// NewGeoPath creates a new GeoPath with default values.
func NewGeoPath() *GeoPath {
	self := GeoPath{}
	self.SetDefaults()
	return &self
}

func (t *GeoPath) Clone() *GeoPath {
	c := &GeoPath{}
	c.Header = *t.Header.Clone()
	if t.Poses != nil {
		c.Poses = make([]GeoPoseStamped, len(t.Poses))
		CloneGeoPoseStampedSlice(c.Poses, t.Poses)
	}
	return c
}

func (t *GeoPath) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GeoPath) SetDefaults() {
	t.Header.SetDefaults()
	t.Poses = nil
}

// CloneGeoPathSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGeoPathSlice(dst, src []GeoPath) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GeoPathTypeSupport types.MessageTypeSupport = _GeoPathTypeSupport{}

type _GeoPathTypeSupport struct{}

func (t _GeoPathTypeSupport) New() types.Message {
	return NewGeoPath()
}

func (t _GeoPathTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__GeoPath
	return (unsafe.Pointer)(C.geographic_msgs__msg__GeoPath__create())
}

func (t _GeoPathTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__GeoPath__destroy((*C.geographic_msgs__msg__GeoPath)(pointer_to_free))
}

func (t _GeoPathTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GeoPath)
	mem := (*C.geographic_msgs__msg__GeoPath)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	GeoPoseStamped__Sequence_to_C(&mem.poses, m.Poses)
}

func (t _GeoPathTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GeoPath)
	mem := (*C.geographic_msgs__msg__GeoPath)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	GeoPoseStamped__Sequence_to_Go(&m.Poses, mem.poses)
}

func (t _GeoPathTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__GeoPath())
}

type CGeoPath = C.geographic_msgs__msg__GeoPath
type CGeoPath__Sequence = C.geographic_msgs__msg__GeoPath__Sequence

func GeoPath__Sequence_to_Go(goSlice *[]GeoPath, cSlice CGeoPath__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GeoPath, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__msg__GeoPath__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPath * uintptr(i)),
		))
		GeoPathTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GeoPath__Sequence_to_C(cSlice *CGeoPath__Sequence, goSlice []GeoPath) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__GeoPath)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__msg__GeoPath * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__msg__GeoPath)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__GeoPath * uintptr(i)),
		))
		GeoPathTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GeoPath__Array_to_Go(goSlice []GeoPath, cSlice []CGeoPath) {
	for i := 0; i < len(cSlice); i++ {
		GeoPathTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GeoPath__Array_to_C(cSlice []CGeoPath, goSlice []GeoPath) {
	for i := 0; i < len(goSlice); i++ {
		GeoPathTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
