/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	unique_identifier_msgs_msg "github.com/tiiuae/rclgo-msgs/unique_identifier_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lunique_identifier_msgs__rosidl_typesupport_c -lunique_identifier_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/msg/map_feature.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/MapFeature", MapFeatureTypeSupport)
}

// Do not create instances of this type directly. Always use NewMapFeature
// function instead.
type MapFeature struct {
	Id unique_identifier_msgs_msg.UUID `yaml:"id"`// Unique feature identifier
	Components []unique_identifier_msgs_msg.UUID `yaml:"components"`// Sequence of feature components
	Props []KeyValue `yaml:"props"`// Key/value properties for this feature
}

// NewMapFeature creates a new MapFeature with default values.
func NewMapFeature() *MapFeature {
	self := MapFeature{}
	self.SetDefaults()
	return &self
}

func (t *MapFeature) Clone() *MapFeature {
	c := &MapFeature{}
	c.Id = *t.Id.Clone()
	if t.Components != nil {
		c.Components = make([]unique_identifier_msgs_msg.UUID, len(t.Components))
		unique_identifier_msgs_msg.CloneUUIDSlice(c.Components, t.Components)
	}
	if t.Props != nil {
		c.Props = make([]KeyValue, len(t.Props))
		CloneKeyValueSlice(c.Props, t.Props)
	}
	return c
}

func (t *MapFeature) CloneMsg() types.Message {
	return t.Clone()
}

func (t *MapFeature) SetDefaults() {
	t.Id.SetDefaults()
	t.Components = nil
	t.Props = nil
}

// CloneMapFeatureSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneMapFeatureSlice(dst, src []MapFeature) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var MapFeatureTypeSupport types.MessageTypeSupport = _MapFeatureTypeSupport{}

type _MapFeatureTypeSupport struct{}

func (t _MapFeatureTypeSupport) New() types.Message {
	return NewMapFeature()
}

func (t _MapFeatureTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__msg__MapFeature
	return (unsafe.Pointer)(C.geographic_msgs__msg__MapFeature__create())
}

func (t _MapFeatureTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__msg__MapFeature__destroy((*C.geographic_msgs__msg__MapFeature)(pointer_to_free))
}

func (t _MapFeatureTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*MapFeature)
	mem := (*C.geographic_msgs__msg__MapFeature)(dst)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsCStruct(unsafe.Pointer(&mem.id), &m.Id)
	unique_identifier_msgs_msg.UUID__Sequence_to_C((*unique_identifier_msgs_msg.CUUID__Sequence)(unsafe.Pointer(&mem.components)), m.Components)
	KeyValue__Sequence_to_C(&mem.props, m.Props)
}

func (t _MapFeatureTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*MapFeature)
	mem := (*C.geographic_msgs__msg__MapFeature)(ros2_message_buffer)
	unique_identifier_msgs_msg.UUIDTypeSupport.AsGoStruct(&m.Id, unsafe.Pointer(&mem.id))
	unique_identifier_msgs_msg.UUID__Sequence_to_Go(&m.Components, *(*unique_identifier_msgs_msg.CUUID__Sequence)(unsafe.Pointer(&mem.components)))
	KeyValue__Sequence_to_Go(&m.Props, mem.props)
}

func (t _MapFeatureTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__msg__MapFeature())
}

type CMapFeature = C.geographic_msgs__msg__MapFeature
type CMapFeature__Sequence = C.geographic_msgs__msg__MapFeature__Sequence

func MapFeature__Sequence_to_Go(goSlice *[]MapFeature, cSlice CMapFeature__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]MapFeature, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__msg__MapFeature__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__MapFeature * uintptr(i)),
		))
		MapFeatureTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func MapFeature__Sequence_to_C(cSlice *CMapFeature__Sequence, goSlice []MapFeature) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__msg__MapFeature)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__msg__MapFeature * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__msg__MapFeature)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__msg__MapFeature * uintptr(i)),
		))
		MapFeatureTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func MapFeature__Array_to_Go(goSlice []MapFeature, cSlice []CMapFeature) {
	for i := 0; i < len(cSlice); i++ {
		MapFeatureTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func MapFeature__Array_to_C(cSlice []CMapFeature, goSlice []MapFeature) {
	for i := 0; i < len(goSlice); i++ {
		MapFeatureTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
