/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geographic_msgs_msg "github.com/tiiuae/rclgo-msgs/geographic_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/get_geographic_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/GetGeographicMap_Response", GetGeographicMap_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetGeographicMap_Response
// function instead.
type GetGeographicMap_Response struct {
	Success bool `yaml:"success"`// true if the call succeeded
	Status string `yaml:"status"`// more details
	Map geographic_msgs_msg.GeographicMap `yaml:"map"`// The requested map, its bounds may differ from the requested bounds.
}

// NewGetGeographicMap_Response creates a new GetGeographicMap_Response with default values.
func NewGetGeographicMap_Response() *GetGeographicMap_Response {
	self := GetGeographicMap_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetGeographicMap_Response) Clone() *GetGeographicMap_Response {
	c := &GetGeographicMap_Response{}
	c.Success = t.Success
	c.Status = t.Status
	c.Map = *t.Map.Clone()
	return c
}

func (t *GetGeographicMap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetGeographicMap_Response) SetDefaults() {
	t.Success = false
	t.Status = ""
	t.Map.SetDefaults()
}

// CloneGetGeographicMap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetGeographicMap_ResponseSlice(dst, src []GetGeographicMap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetGeographicMap_ResponseTypeSupport types.MessageTypeSupport = _GetGeographicMap_ResponseTypeSupport{}

type _GetGeographicMap_ResponseTypeSupport struct{}

func (t _GetGeographicMap_ResponseTypeSupport) New() types.Message {
	return NewGetGeographicMap_Response()
}

func (t _GetGeographicMap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__GetGeographicMap_Response
	return (unsafe.Pointer)(C.geographic_msgs__srv__GetGeographicMap_Response__create())
}

func (t _GetGeographicMap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__GetGeographicMap_Response__destroy((*C.geographic_msgs__srv__GetGeographicMap_Response)(pointer_to_free))
}

func (t _GetGeographicMap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__GetGeographicMap_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status), m.Status)
	geographic_msgs_msg.GeographicMapTypeSupport.AsCStruct(unsafe.Pointer(&mem._map), &m.Map)
}

func (t _GetGeographicMap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__GetGeographicMap_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Status, unsafe.Pointer(&mem.status))
	geographic_msgs_msg.GeographicMapTypeSupport.AsGoStruct(&m.Map, unsafe.Pointer(&mem._map))
}

func (t _GetGeographicMap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__GetGeographicMap_Response())
}

type CGetGeographicMap_Response = C.geographic_msgs__srv__GetGeographicMap_Response
type CGetGeographicMap_Response__Sequence = C.geographic_msgs__srv__GetGeographicMap_Response__Sequence

func GetGeographicMap_Response__Sequence_to_Go(goSlice *[]GetGeographicMap_Response, cSlice CGetGeographicMap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetGeographicMap_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__srv__GetGeographicMap_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__GetGeographicMap_Response * uintptr(i)),
		))
		GetGeographicMap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetGeographicMap_Response__Sequence_to_C(cSlice *CGetGeographicMap_Response__Sequence, goSlice []GetGeographicMap_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__GetGeographicMap_Response)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__srv__GetGeographicMap_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__srv__GetGeographicMap_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__GetGeographicMap_Response * uintptr(i)),
		))
		GetGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetGeographicMap_Response__Array_to_Go(goSlice []GetGeographicMap_Response, cSlice []CGetGeographicMap_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetGeographicMap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetGeographicMap_Response__Array_to_C(cSlice []CGetGeographicMap_Response, goSlice []GetGeographicMap_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
