/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geographic_msgs_msg "github.com/tiiuae/rclgo-msgs/geographic_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/update_geographic_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/UpdateGeographicMap_Request", UpdateGeographicMap_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewUpdateGeographicMap_Request
// function instead.
type UpdateGeographicMap_Request struct {
	Updates geographic_msgs_msg.GeographicMapChanges `yaml:"updates"`// Changes to geographic map.
}

// NewUpdateGeographicMap_Request creates a new UpdateGeographicMap_Request with default values.
func NewUpdateGeographicMap_Request() *UpdateGeographicMap_Request {
	self := UpdateGeographicMap_Request{}
	self.SetDefaults()
	return &self
}

func (t *UpdateGeographicMap_Request) Clone() *UpdateGeographicMap_Request {
	c := &UpdateGeographicMap_Request{}
	c.Updates = *t.Updates.Clone()
	return c
}

func (t *UpdateGeographicMap_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UpdateGeographicMap_Request) SetDefaults() {
	t.Updates.SetDefaults()
}

// CloneUpdateGeographicMap_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUpdateGeographicMap_RequestSlice(dst, src []UpdateGeographicMap_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UpdateGeographicMap_RequestTypeSupport types.MessageTypeSupport = _UpdateGeographicMap_RequestTypeSupport{}

type _UpdateGeographicMap_RequestTypeSupport struct{}

func (t _UpdateGeographicMap_RequestTypeSupport) New() types.Message {
	return NewUpdateGeographicMap_Request()
}

func (t _UpdateGeographicMap_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__UpdateGeographicMap_Request
	return (unsafe.Pointer)(C.geographic_msgs__srv__UpdateGeographicMap_Request__create())
}

func (t _UpdateGeographicMap_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__UpdateGeographicMap_Request__destroy((*C.geographic_msgs__srv__UpdateGeographicMap_Request)(pointer_to_free))
}

func (t _UpdateGeographicMap_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UpdateGeographicMap_Request)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(dst)
	geographic_msgs_msg.GeographicMapChangesTypeSupport.AsCStruct(unsafe.Pointer(&mem.updates), &m.Updates)
}

func (t _UpdateGeographicMap_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UpdateGeographicMap_Request)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(ros2_message_buffer)
	geographic_msgs_msg.GeographicMapChangesTypeSupport.AsGoStruct(&m.Updates, unsafe.Pointer(&mem.updates))
}

func (t _UpdateGeographicMap_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__UpdateGeographicMap_Request())
}

type CUpdateGeographicMap_Request = C.geographic_msgs__srv__UpdateGeographicMap_Request
type CUpdateGeographicMap_Request__Sequence = C.geographic_msgs__srv__UpdateGeographicMap_Request__Sequence

func UpdateGeographicMap_Request__Sequence_to_Go(goSlice *[]UpdateGeographicMap_Request, cSlice CUpdateGeographicMap_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UpdateGeographicMap_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__srv__UpdateGeographicMap_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Request * uintptr(i)),
		))
		UpdateGeographicMap_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func UpdateGeographicMap_Request__Sequence_to_C(cSlice *CUpdateGeographicMap_Request__Sequence, goSlice []UpdateGeographicMap_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__srv__UpdateGeographicMap_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Request * uintptr(i)),
		))
		UpdateGeographicMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func UpdateGeographicMap_Request__Array_to_Go(goSlice []UpdateGeographicMap_Request, cSlice []CUpdateGeographicMap_Request) {
	for i := 0; i < len(cSlice); i++ {
		UpdateGeographicMap_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UpdateGeographicMap_Request__Array_to_C(cSlice []CUpdateGeographicMap_Request, goSlice []UpdateGeographicMap_Request) {
	for i := 0; i < len(goSlice); i++ {
		UpdateGeographicMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
