/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package geographic_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgeographic_msgs__rosidl_typesupport_c -lgeographic_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <geographic_msgs/srv/update_geographic_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("geographic_msgs/UpdateGeographicMap_Response", UpdateGeographicMap_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewUpdateGeographicMap_Response
// function instead.
type UpdateGeographicMap_Response struct {
	Success bool `yaml:"success"`// true if the call succeeded
	Status string `yaml:"status"`// more details
}

// NewUpdateGeographicMap_Response creates a new UpdateGeographicMap_Response with default values.
func NewUpdateGeographicMap_Response() *UpdateGeographicMap_Response {
	self := UpdateGeographicMap_Response{}
	self.SetDefaults()
	return &self
}

func (t *UpdateGeographicMap_Response) Clone() *UpdateGeographicMap_Response {
	c := &UpdateGeographicMap_Response{}
	c.Success = t.Success
	c.Status = t.Status
	return c
}

func (t *UpdateGeographicMap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *UpdateGeographicMap_Response) SetDefaults() {
	t.Success = false
	t.Status = ""
}

// CloneUpdateGeographicMap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneUpdateGeographicMap_ResponseSlice(dst, src []UpdateGeographicMap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var UpdateGeographicMap_ResponseTypeSupport types.MessageTypeSupport = _UpdateGeographicMap_ResponseTypeSupport{}

type _UpdateGeographicMap_ResponseTypeSupport struct{}

func (t _UpdateGeographicMap_ResponseTypeSupport) New() types.Message {
	return NewUpdateGeographicMap_Response()
}

func (t _UpdateGeographicMap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.geographic_msgs__srv__UpdateGeographicMap_Response
	return (unsafe.Pointer)(C.geographic_msgs__srv__UpdateGeographicMap_Response__create())
}

func (t _UpdateGeographicMap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.geographic_msgs__srv__UpdateGeographicMap_Response__destroy((*C.geographic_msgs__srv__UpdateGeographicMap_Response)(pointer_to_free))
}

func (t _UpdateGeographicMap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*UpdateGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status), m.Status)
}

func (t _UpdateGeographicMap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*UpdateGeographicMap_Response)
	mem := (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.Status, unsafe.Pointer(&mem.status))
}

func (t _UpdateGeographicMap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__geographic_msgs__srv__UpdateGeographicMap_Response())
}

type CUpdateGeographicMap_Response = C.geographic_msgs__srv__UpdateGeographicMap_Response
type CUpdateGeographicMap_Response__Sequence = C.geographic_msgs__srv__UpdateGeographicMap_Response__Sequence

func UpdateGeographicMap_Response__Sequence_to_Go(goSlice *[]UpdateGeographicMap_Response, cSlice CUpdateGeographicMap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]UpdateGeographicMap_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.geographic_msgs__srv__UpdateGeographicMap_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Response * uintptr(i)),
		))
		UpdateGeographicMap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func UpdateGeographicMap_Response__Sequence_to_C(cSlice *CUpdateGeographicMap_Response__Sequence, goSlice []UpdateGeographicMap_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(C.malloc((C.size_t)(C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.geographic_msgs__srv__UpdateGeographicMap_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_geographic_msgs__srv__UpdateGeographicMap_Response * uintptr(i)),
		))
		UpdateGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func UpdateGeographicMap_Response__Array_to_Go(goSlice []UpdateGeographicMap_Response, cSlice []CUpdateGeographicMap_Response) {
	for i := 0; i < len(cSlice); i++ {
		UpdateGeographicMap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func UpdateGeographicMap_Response__Array_to_C(cSlice []CUpdateGeographicMap_Response, goSlice []UpdateGeographicMap_Response) {
	for i := 0; i < len(goSlice); i++ {
		UpdateGeographicMap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
