/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package octomap_msgs_msg
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/geometry_msgs/msg"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -loctomap_msgs__rosidl_typesupport_c -loctomap_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <octomap_msgs/msg/octomap_with_pose.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("octomap_msgs/OctomapWithPose", OctomapWithPoseTypeSupport)
}

// Do not create instances of this type directly. Always use NewOctomapWithPose
// function instead.
type OctomapWithPose struct {
	Header std_msgs_msg.Header `yaml:"header"`// A 3D map in binary format, as Octree
	Origin geometry_msgs_msg.Pose `yaml:"origin"`// The pose of the octree with respect to the header frame
	Octomap Octomap `yaml:"octomap"`// The actual octree msg
}

// NewOctomapWithPose creates a new OctomapWithPose with default values.
func NewOctomapWithPose() *OctomapWithPose {
	self := OctomapWithPose{}
	self.SetDefaults()
	return &self
}

func (t *OctomapWithPose) Clone() *OctomapWithPose {
	c := &OctomapWithPose{}
	c.Header = *t.Header.Clone()
	c.Origin = *t.Origin.Clone()
	c.Octomap = *t.Octomap.Clone()
	return c
}

func (t *OctomapWithPose) CloneMsg() types.Message {
	return t.Clone()
}

func (t *OctomapWithPose) SetDefaults() {
	t.Header.SetDefaults()
	t.Origin.SetDefaults()
	t.Octomap.SetDefaults()
}

// CloneOctomapWithPoseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneOctomapWithPoseSlice(dst, src []OctomapWithPose) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var OctomapWithPoseTypeSupport types.MessageTypeSupport = _OctomapWithPoseTypeSupport{}

type _OctomapWithPoseTypeSupport struct{}

func (t _OctomapWithPoseTypeSupport) New() types.Message {
	return NewOctomapWithPose()
}

func (t _OctomapWithPoseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.octomap_msgs__msg__OctomapWithPose
	return (unsafe.Pointer)(C.octomap_msgs__msg__OctomapWithPose__create())
}

func (t _OctomapWithPoseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.octomap_msgs__msg__OctomapWithPose__destroy((*C.octomap_msgs__msg__OctomapWithPose)(pointer_to_free))
}

func (t _OctomapWithPoseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*OctomapWithPose)
	mem := (*C.octomap_msgs__msg__OctomapWithPose)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	geometry_msgs_msg.PoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.origin), &m.Origin)
	OctomapTypeSupport.AsCStruct(unsafe.Pointer(&mem.octomap), &m.Octomap)
}

func (t _OctomapWithPoseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*OctomapWithPose)
	mem := (*C.octomap_msgs__msg__OctomapWithPose)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	geometry_msgs_msg.PoseTypeSupport.AsGoStruct(&m.Origin, unsafe.Pointer(&mem.origin))
	OctomapTypeSupport.AsGoStruct(&m.Octomap, unsafe.Pointer(&mem.octomap))
}

func (t _OctomapWithPoseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__octomap_msgs__msg__OctomapWithPose())
}

type COctomapWithPose = C.octomap_msgs__msg__OctomapWithPose
type COctomapWithPose__Sequence = C.octomap_msgs__msg__OctomapWithPose__Sequence

func OctomapWithPose__Sequence_to_Go(goSlice *[]OctomapWithPose, cSlice COctomapWithPose__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]OctomapWithPose, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.octomap_msgs__msg__OctomapWithPose__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__msg__OctomapWithPose * uintptr(i)),
		))
		OctomapWithPoseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func OctomapWithPose__Sequence_to_C(cSlice *COctomapWithPose__Sequence, goSlice []OctomapWithPose) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.octomap_msgs__msg__OctomapWithPose)(C.malloc((C.size_t)(C.sizeof_struct_octomap_msgs__msg__OctomapWithPose * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.octomap_msgs__msg__OctomapWithPose)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__msg__OctomapWithPose * uintptr(i)),
		))
		OctomapWithPoseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func OctomapWithPose__Array_to_Go(goSlice []OctomapWithPose, cSlice []COctomapWithPose) {
	for i := 0; i < len(cSlice); i++ {
		OctomapWithPoseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func OctomapWithPose__Array_to_C(cSlice []COctomapWithPose, goSlice []OctomapWithPose) {
	for i := 0; i < len(goSlice); i++ {
		OctomapWithPoseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
