/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package octomap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	octomap_msgs_msg "github.com/tiiuae/rclgo-msgs/octomap_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -loctomap_msgs__rosidl_typesupport_c -loctomap_msgs__rosidl_generator_c
#cgo LDFLAGS: -loctomap_msgs__rosidl_typesupport_c -loctomap_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <octomap_msgs/srv/get_octomap.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("octomap_msgs/GetOctomap_Response", GetOctomap_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetOctomap_Response
// function instead.
type GetOctomap_Response struct {
	Map octomap_msgs_msg.Octomap `yaml:"map"`// Get the map as a octomap
}

// NewGetOctomap_Response creates a new GetOctomap_Response with default values.
func NewGetOctomap_Response() *GetOctomap_Response {
	self := GetOctomap_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetOctomap_Response) Clone() *GetOctomap_Response {
	c := &GetOctomap_Response{}
	c.Map = *t.Map.Clone()
	return c
}

func (t *GetOctomap_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetOctomap_Response) SetDefaults() {
	t.Map.SetDefaults()
}

// CloneGetOctomap_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetOctomap_ResponseSlice(dst, src []GetOctomap_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetOctomap_ResponseTypeSupport types.MessageTypeSupport = _GetOctomap_ResponseTypeSupport{}

type _GetOctomap_ResponseTypeSupport struct{}

func (t _GetOctomap_ResponseTypeSupport) New() types.Message {
	return NewGetOctomap_Response()
}

func (t _GetOctomap_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.octomap_msgs__srv__GetOctomap_Response
	return (unsafe.Pointer)(C.octomap_msgs__srv__GetOctomap_Response__create())
}

func (t _GetOctomap_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.octomap_msgs__srv__GetOctomap_Response__destroy((*C.octomap_msgs__srv__GetOctomap_Response)(pointer_to_free))
}

func (t _GetOctomap_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetOctomap_Response)
	mem := (*C.octomap_msgs__srv__GetOctomap_Response)(dst)
	octomap_msgs_msg.OctomapTypeSupport.AsCStruct(unsafe.Pointer(&mem._map), &m.Map)
}

func (t _GetOctomap_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetOctomap_Response)
	mem := (*C.octomap_msgs__srv__GetOctomap_Response)(ros2_message_buffer)
	octomap_msgs_msg.OctomapTypeSupport.AsGoStruct(&m.Map, unsafe.Pointer(&mem._map))
}

func (t _GetOctomap_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__octomap_msgs__srv__GetOctomap_Response())
}

type CGetOctomap_Response = C.octomap_msgs__srv__GetOctomap_Response
type CGetOctomap_Response__Sequence = C.octomap_msgs__srv__GetOctomap_Response__Sequence

func GetOctomap_Response__Sequence_to_Go(goSlice *[]GetOctomap_Response, cSlice CGetOctomap_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetOctomap_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.octomap_msgs__srv__GetOctomap_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__srv__GetOctomap_Response * uintptr(i)),
		))
		GetOctomap_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetOctomap_Response__Sequence_to_C(cSlice *CGetOctomap_Response__Sequence, goSlice []GetOctomap_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.octomap_msgs__srv__GetOctomap_Response)(C.malloc((C.size_t)(C.sizeof_struct_octomap_msgs__srv__GetOctomap_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.octomap_msgs__srv__GetOctomap_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__srv__GetOctomap_Response * uintptr(i)),
		))
		GetOctomap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetOctomap_Response__Array_to_Go(goSlice []GetOctomap_Response, cSlice []CGetOctomap_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetOctomap_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetOctomap_Response__Array_to_C(cSlice []CGetOctomap_Response, goSlice []GetOctomap_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetOctomap_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
