/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package octomap_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -loctomap_msgs__rosidl_typesupport_c -loctomap_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <octomap_msgs/srv/get_octomap.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("octomap_msgs/GetOctomap_Request", GetOctomap_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetOctomap_Request
// function instead.
type GetOctomap_Request struct {
}

// NewGetOctomap_Request creates a new GetOctomap_Request with default values.
func NewGetOctomap_Request() *GetOctomap_Request {
	self := GetOctomap_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetOctomap_Request) Clone() *GetOctomap_Request {
	c := &GetOctomap_Request{}
	return c
}

func (t *GetOctomap_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetOctomap_Request) SetDefaults() {
}

// CloneGetOctomap_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetOctomap_RequestSlice(dst, src []GetOctomap_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetOctomap_RequestTypeSupport types.MessageTypeSupport = _GetOctomap_RequestTypeSupport{}

type _GetOctomap_RequestTypeSupport struct{}

func (t _GetOctomap_RequestTypeSupport) New() types.Message {
	return NewGetOctomap_Request()
}

func (t _GetOctomap_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.octomap_msgs__srv__GetOctomap_Request
	return (unsafe.Pointer)(C.octomap_msgs__srv__GetOctomap_Request__create())
}

func (t _GetOctomap_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.octomap_msgs__srv__GetOctomap_Request__destroy((*C.octomap_msgs__srv__GetOctomap_Request)(pointer_to_free))
}

func (t _GetOctomap_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetOctomap_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetOctomap_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__octomap_msgs__srv__GetOctomap_Request())
}

type CGetOctomap_Request = C.octomap_msgs__srv__GetOctomap_Request
type CGetOctomap_Request__Sequence = C.octomap_msgs__srv__GetOctomap_Request__Sequence

func GetOctomap_Request__Sequence_to_Go(goSlice *[]GetOctomap_Request, cSlice CGetOctomap_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetOctomap_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.octomap_msgs__srv__GetOctomap_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__srv__GetOctomap_Request * uintptr(i)),
		))
		GetOctomap_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetOctomap_Request__Sequence_to_C(cSlice *CGetOctomap_Request__Sequence, goSlice []GetOctomap_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.octomap_msgs__srv__GetOctomap_Request)(C.malloc((C.size_t)(C.sizeof_struct_octomap_msgs__srv__GetOctomap_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.octomap_msgs__srv__GetOctomap_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_octomap_msgs__srv__GetOctomap_Request * uintptr(i)),
		))
		GetOctomap_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetOctomap_Request__Array_to_Go(goSlice []GetOctomap_Request, cSlice []CGetOctomap_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetOctomap_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetOctomap_Request__Array_to_C(cSlice []CGetOctomap_Request, goSlice []GetOctomap_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetOctomap_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
