/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package octomap_msgs_srv

/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -loctomap_msgs__rosidl_typesupport_c -loctomap_msgs__rosidl_generator_c
#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>
#include <octomap_msgs/srv/get_octomap.h>
*/
import "C"

import (
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	"github.com/tiiuae/rclgo/pkg/rclgo/types"

	"unsafe"
)

func init() {
	typemap.RegisterService("octomap_msgs/GetOctomap", GetOctomapTypeSupport)
}

type _GetOctomapTypeSupport struct {}

func (s _GetOctomapTypeSupport) Request() types.MessageTypeSupport {
	return GetOctomap_RequestTypeSupport
}

func (s _GetOctomapTypeSupport) Response() types.MessageTypeSupport {
	return GetOctomap_ResponseTypeSupport
}

func (s _GetOctomapTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_service_type_support_handle__octomap_msgs__srv__GetOctomap())
}

// Modifying this variable is undefined behavior.
var GetOctomapTypeSupport types.ServiceTypeSupport = _GetOctomapTypeSupport{}
