/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package nav_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lnav_msgs__rosidl_typesupport_c -lnav_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <nav_msgs/srv/load_map.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("nav_msgs/LoadMap_Request", LoadMap_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewLoadMap_Request
// function instead.
type LoadMap_Request struct {
	MapUrl string `yaml:"map_url"`// URL of map resourceCan be an absolute path to a file: file:///path/to/maps/floor1.yamlOr, relative to a ROS package: package://my_ros_package/maps/floor2.yaml
}

// NewLoadMap_Request creates a new LoadMap_Request with default values.
func NewLoadMap_Request() *LoadMap_Request {
	self := LoadMap_Request{}
	self.SetDefaults()
	return &self
}

func (t *LoadMap_Request) Clone() *LoadMap_Request {
	c := &LoadMap_Request{}
	c.MapUrl = t.MapUrl
	return c
}

func (t *LoadMap_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *LoadMap_Request) SetDefaults() {
	t.MapUrl = ""
}

// CloneLoadMap_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneLoadMap_RequestSlice(dst, src []LoadMap_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var LoadMap_RequestTypeSupport types.MessageTypeSupport = _LoadMap_RequestTypeSupport{}

type _LoadMap_RequestTypeSupport struct{}

func (t _LoadMap_RequestTypeSupport) New() types.Message {
	return NewLoadMap_Request()
}

func (t _LoadMap_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.nav_msgs__srv__LoadMap_Request
	return (unsafe.Pointer)(C.nav_msgs__srv__LoadMap_Request__create())
}

func (t _LoadMap_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.nav_msgs__srv__LoadMap_Request__destroy((*C.nav_msgs__srv__LoadMap_Request)(pointer_to_free))
}

func (t _LoadMap_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*LoadMap_Request)
	mem := (*C.nav_msgs__srv__LoadMap_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.map_url), m.MapUrl)
}

func (t _LoadMap_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*LoadMap_Request)
	mem := (*C.nav_msgs__srv__LoadMap_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.MapUrl, unsafe.Pointer(&mem.map_url))
}

func (t _LoadMap_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__nav_msgs__srv__LoadMap_Request())
}

type CLoadMap_Request = C.nav_msgs__srv__LoadMap_Request
type CLoadMap_Request__Sequence = C.nav_msgs__srv__LoadMap_Request__Sequence

func LoadMap_Request__Sequence_to_Go(goSlice *[]LoadMap_Request, cSlice CLoadMap_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]LoadMap_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.nav_msgs__srv__LoadMap_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_nav_msgs__srv__LoadMap_Request * uintptr(i)),
		))
		LoadMap_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func LoadMap_Request__Sequence_to_C(cSlice *CLoadMap_Request__Sequence, goSlice []LoadMap_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.nav_msgs__srv__LoadMap_Request)(C.malloc((C.size_t)(C.sizeof_struct_nav_msgs__srv__LoadMap_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.nav_msgs__srv__LoadMap_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_nav_msgs__srv__LoadMap_Request * uintptr(i)),
		))
		LoadMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func LoadMap_Request__Array_to_Go(goSlice []LoadMap_Request, cSlice []CLoadMap_Request) {
	for i := 0; i < len(cSlice); i++ {
		LoadMap_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func LoadMap_Request__Array_to_C(cSlice []CLoadMap_Request, goSlice []LoadMap_Request) {
	for i := 0; i < len(goSlice); i++ {
		LoadMap_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
