/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	builtin_interfaces_msg "github.com/mehmetkillioglu/rclgo-msgs/builtin_interfaces/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lbuiltin_interfaces__rosidl_typesupport_c -lbuiltin_interfaces__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/apply_joint_effort.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/ApplyJointEffort_Request", ApplyJointEffort_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewApplyJointEffort_Request
// function instead.
type ApplyJointEffort_Request struct {
	JointName string `yaml:"joint_name"`// joint to apply wrench (linear force and torque). set urdf joint effort
	Effort float64 `yaml:"effort"`// effort to apply. set urdf joint effort
	StartTime builtin_interfaces_msg.Time `yaml:"start_time"`// optional wrench application start time (seconds). set urdf joint effort
	Duration builtin_interfaces_msg.Duration `yaml:"duration"`// optional duration of wrench application time (seconds). set urdf joint effortif start_time < current time, start as soon as possible
}

// NewApplyJointEffort_Request creates a new ApplyJointEffort_Request with default values.
func NewApplyJointEffort_Request() *ApplyJointEffort_Request {
	self := ApplyJointEffort_Request{}
	self.SetDefaults()
	return &self
}

func (t *ApplyJointEffort_Request) Clone() *ApplyJointEffort_Request {
	c := &ApplyJointEffort_Request{}
	c.JointName = t.JointName
	c.Effort = t.Effort
	c.StartTime = *t.StartTime.Clone()
	c.Duration = *t.Duration.Clone()
	return c
}

func (t *ApplyJointEffort_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ApplyJointEffort_Request) SetDefaults() {
	t.JointName = ""
	t.Effort = 0
	t.StartTime.SetDefaults()
	t.Duration.SetDefaults()
}

// CloneApplyJointEffort_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneApplyJointEffort_RequestSlice(dst, src []ApplyJointEffort_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ApplyJointEffort_RequestTypeSupport types.MessageTypeSupport = _ApplyJointEffort_RequestTypeSupport{}

type _ApplyJointEffort_RequestTypeSupport struct{}

func (t _ApplyJointEffort_RequestTypeSupport) New() types.Message {
	return NewApplyJointEffort_Request()
}

func (t _ApplyJointEffort_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__ApplyJointEffort_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__ApplyJointEffort_Request__create())
}

func (t _ApplyJointEffort_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__ApplyJointEffort_Request__destroy((*C.gazebo_msgs__srv__ApplyJointEffort_Request)(pointer_to_free))
}

func (t _ApplyJointEffort_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ApplyJointEffort_Request)
	mem := (*C.gazebo_msgs__srv__ApplyJointEffort_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.joint_name), m.JointName)
	mem.effort = C.double(m.Effort)
	builtin_interfaces_msg.TimeTypeSupport.AsCStruct(unsafe.Pointer(&mem.start_time), &m.StartTime)
	builtin_interfaces_msg.DurationTypeSupport.AsCStruct(unsafe.Pointer(&mem.duration), &m.Duration)
}

func (t _ApplyJointEffort_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ApplyJointEffort_Request)
	mem := (*C.gazebo_msgs__srv__ApplyJointEffort_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.JointName, unsafe.Pointer(&mem.joint_name))
	m.Effort = float64(mem.effort)
	builtin_interfaces_msg.TimeTypeSupport.AsGoStruct(&m.StartTime, unsafe.Pointer(&mem.start_time))
	builtin_interfaces_msg.DurationTypeSupport.AsGoStruct(&m.Duration, unsafe.Pointer(&mem.duration))
}

func (t _ApplyJointEffort_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__ApplyJointEffort_Request())
}

type CApplyJointEffort_Request = C.gazebo_msgs__srv__ApplyJointEffort_Request
type CApplyJointEffort_Request__Sequence = C.gazebo_msgs__srv__ApplyJointEffort_Request__Sequence

func ApplyJointEffort_Request__Sequence_to_Go(goSlice *[]ApplyJointEffort_Request, cSlice CApplyJointEffort_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ApplyJointEffort_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__ApplyJointEffort_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Request * uintptr(i)),
		))
		ApplyJointEffort_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ApplyJointEffort_Request__Sequence_to_C(cSlice *CApplyJointEffort_Request__Sequence, goSlice []ApplyJointEffort_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__ApplyJointEffort_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__ApplyJointEffort_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Request * uintptr(i)),
		))
		ApplyJointEffort_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ApplyJointEffort_Request__Array_to_Go(goSlice []ApplyJointEffort_Request, cSlice []CApplyJointEffort_Request) {
	for i := 0; i < len(cSlice); i++ {
		ApplyJointEffort_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ApplyJointEffort_Request__Array_to_C(cSlice []CApplyJointEffort_Request, goSlice []ApplyJointEffort_Request) {
	for i := 0; i < len(goSlice); i++ {
		ApplyJointEffort_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
