/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/apply_joint_effort.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/ApplyJointEffort_Response", ApplyJointEffort_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewApplyJointEffort_Response
// function instead.
type ApplyJointEffort_Response struct {
	Success bool `yaml:"success"`// return true if effort application is successful. set urdf joint effortif start_time < current time, start as soon as possibleif duration < 0, apply wrench continuously without endif duration = 0, do nothingif duration < step size, assume step size anddisplay warning in status_message
	StatusMessage string `yaml:"status_message"`// comments if available. set urdf joint effortif start_time < current time, start as soon as possibleif duration < 0, apply wrench continuously without endif duration = 0, do nothingif duration < step size, assume step size anddisplay warning in status_message
}

// NewApplyJointEffort_Response creates a new ApplyJointEffort_Response with default values.
func NewApplyJointEffort_Response() *ApplyJointEffort_Response {
	self := ApplyJointEffort_Response{}
	self.SetDefaults()
	return &self
}

func (t *ApplyJointEffort_Response) Clone() *ApplyJointEffort_Response {
	c := &ApplyJointEffort_Response{}
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *ApplyJointEffort_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *ApplyJointEffort_Response) SetDefaults() {
	t.Success = false
	t.StatusMessage = ""
}

// CloneApplyJointEffort_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneApplyJointEffort_ResponseSlice(dst, src []ApplyJointEffort_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var ApplyJointEffort_ResponseTypeSupport types.MessageTypeSupport = _ApplyJointEffort_ResponseTypeSupport{}

type _ApplyJointEffort_ResponseTypeSupport struct{}

func (t _ApplyJointEffort_ResponseTypeSupport) New() types.Message {
	return NewApplyJointEffort_Response()
}

func (t _ApplyJointEffort_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__ApplyJointEffort_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__ApplyJointEffort_Response__create())
}

func (t _ApplyJointEffort_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__ApplyJointEffort_Response__destroy((*C.gazebo_msgs__srv__ApplyJointEffort_Response)(pointer_to_free))
}

func (t _ApplyJointEffort_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*ApplyJointEffort_Response)
	mem := (*C.gazebo_msgs__srv__ApplyJointEffort_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _ApplyJointEffort_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*ApplyJointEffort_Response)
	mem := (*C.gazebo_msgs__srv__ApplyJointEffort_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _ApplyJointEffort_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__ApplyJointEffort_Response())
}

type CApplyJointEffort_Response = C.gazebo_msgs__srv__ApplyJointEffort_Response
type CApplyJointEffort_Response__Sequence = C.gazebo_msgs__srv__ApplyJointEffort_Response__Sequence

func ApplyJointEffort_Response__Sequence_to_Go(goSlice *[]ApplyJointEffort_Response, cSlice CApplyJointEffort_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]ApplyJointEffort_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__ApplyJointEffort_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Response * uintptr(i)),
		))
		ApplyJointEffort_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func ApplyJointEffort_Response__Sequence_to_C(cSlice *CApplyJointEffort_Response__Sequence, goSlice []ApplyJointEffort_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__ApplyJointEffort_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__ApplyJointEffort_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__ApplyJointEffort_Response * uintptr(i)),
		))
		ApplyJointEffort_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func ApplyJointEffort_Response__Array_to_Go(goSlice []ApplyJointEffort_Response, cSlice []CApplyJointEffort_Response) {
	for i := 0; i < len(cSlice); i++ {
		ApplyJointEffort_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func ApplyJointEffort_Response__Array_to_C(cSlice []CApplyJointEffort_Response, goSlice []ApplyJointEffort_Response) {
	for i := 0; i < len(goSlice); i++ {
		ApplyJointEffort_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
