/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/body_request.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/BodyRequest_Response", BodyRequest_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewBodyRequest_Response
// function instead.
type BodyRequest_Response struct {
}

// NewBodyRequest_Response creates a new BodyRequest_Response with default values.
func NewBodyRequest_Response() *BodyRequest_Response {
	self := BodyRequest_Response{}
	self.SetDefaults()
	return &self
}

func (t *BodyRequest_Response) Clone() *BodyRequest_Response {
	c := &BodyRequest_Response{}
	return c
}

func (t *BodyRequest_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *BodyRequest_Response) SetDefaults() {
}

// CloneBodyRequest_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneBodyRequest_ResponseSlice(dst, src []BodyRequest_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var BodyRequest_ResponseTypeSupport types.MessageTypeSupport = _BodyRequest_ResponseTypeSupport{}

type _BodyRequest_ResponseTypeSupport struct{}

func (t _BodyRequest_ResponseTypeSupport) New() types.Message {
	return NewBodyRequest_Response()
}

func (t _BodyRequest_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__BodyRequest_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__BodyRequest_Response__create())
}

func (t _BodyRequest_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__BodyRequest_Response__destroy((*C.gazebo_msgs__srv__BodyRequest_Response)(pointer_to_free))
}

func (t _BodyRequest_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _BodyRequest_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _BodyRequest_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__BodyRequest_Response())
}

type CBodyRequest_Response = C.gazebo_msgs__srv__BodyRequest_Response
type CBodyRequest_Response__Sequence = C.gazebo_msgs__srv__BodyRequest_Response__Sequence

func BodyRequest_Response__Sequence_to_Go(goSlice *[]BodyRequest_Response, cSlice CBodyRequest_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]BodyRequest_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__BodyRequest_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__BodyRequest_Response * uintptr(i)),
		))
		BodyRequest_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func BodyRequest_Response__Sequence_to_C(cSlice *CBodyRequest_Response__Sequence, goSlice []BodyRequest_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__BodyRequest_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__BodyRequest_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__BodyRequest_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__BodyRequest_Response * uintptr(i)),
		))
		BodyRequest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func BodyRequest_Response__Array_to_Go(goSlice []BodyRequest_Response, cSlice []CBodyRequest_Response) {
	for i := 0; i < len(cSlice); i++ {
		BodyRequest_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func BodyRequest_Response__Array_to_C(cSlice []CBodyRequest_Response, goSlice []BodyRequest_Response) {
	for i := 0; i < len(goSlice); i++ {
		BodyRequest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
