/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/delete_entity.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/DeleteEntity_Request", DeleteEntity_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewDeleteEntity_Request
// function instead.
type DeleteEntity_Request struct {
	Name string `yaml:"name"`// Name of the Gazebo entity to be deleted. This can be either
}

// NewDeleteEntity_Request creates a new DeleteEntity_Request with default values.
func NewDeleteEntity_Request() *DeleteEntity_Request {
	self := DeleteEntity_Request{}
	self.SetDefaults()
	return &self
}

func (t *DeleteEntity_Request) Clone() *DeleteEntity_Request {
	c := &DeleteEntity_Request{}
	c.Name = t.Name
	return c
}

func (t *DeleteEntity_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *DeleteEntity_Request) SetDefaults() {
	t.Name = ""
}

// CloneDeleteEntity_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneDeleteEntity_RequestSlice(dst, src []DeleteEntity_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var DeleteEntity_RequestTypeSupport types.MessageTypeSupport = _DeleteEntity_RequestTypeSupport{}

type _DeleteEntity_RequestTypeSupport struct{}

func (t _DeleteEntity_RequestTypeSupport) New() types.Message {
	return NewDeleteEntity_Request()
}

func (t _DeleteEntity_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__DeleteEntity_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__DeleteEntity_Request__create())
}

func (t _DeleteEntity_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__DeleteEntity_Request__destroy((*C.gazebo_msgs__srv__DeleteEntity_Request)(pointer_to_free))
}

func (t _DeleteEntity_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*DeleteEntity_Request)
	mem := (*C.gazebo_msgs__srv__DeleteEntity_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
}

func (t _DeleteEntity_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*DeleteEntity_Request)
	mem := (*C.gazebo_msgs__srv__DeleteEntity_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
}

func (t _DeleteEntity_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__DeleteEntity_Request())
}

type CDeleteEntity_Request = C.gazebo_msgs__srv__DeleteEntity_Request
type CDeleteEntity_Request__Sequence = C.gazebo_msgs__srv__DeleteEntity_Request__Sequence

func DeleteEntity_Request__Sequence_to_Go(goSlice *[]DeleteEntity_Request, cSlice CDeleteEntity_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]DeleteEntity_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__DeleteEntity_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__DeleteEntity_Request * uintptr(i)),
		))
		DeleteEntity_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func DeleteEntity_Request__Sequence_to_C(cSlice *CDeleteEntity_Request__Sequence, goSlice []DeleteEntity_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__DeleteEntity_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__DeleteEntity_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__DeleteEntity_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__DeleteEntity_Request * uintptr(i)),
		))
		DeleteEntity_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func DeleteEntity_Request__Array_to_Go(goSlice []DeleteEntity_Request, cSlice []CDeleteEntity_Request) {
	for i := 0; i < len(cSlice); i++ {
		DeleteEntity_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func DeleteEntity_Request__Array_to_C(cSlice []CDeleteEntity_Request, goSlice []DeleteEntity_Request) {
	for i := 0; i < len(goSlice); i++ {
		DeleteEntity_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
