/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/delete_light.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/DeleteLight_Response", DeleteLight_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewDeleteLight_Response
// function instead.
type DeleteLight_Response struct {
	Success bool `yaml:"success"`// return true if deletion is successful. Deprecated, kept for ROS 1 bridge.Use DeleteEntity
	StatusMessage string `yaml:"status_message"`// comments if available. Deprecated, kept for ROS 1 bridge.Use DeleteEntity
}

// NewDeleteLight_Response creates a new DeleteLight_Response with default values.
func NewDeleteLight_Response() *DeleteLight_Response {
	self := DeleteLight_Response{}
	self.SetDefaults()
	return &self
}

func (t *DeleteLight_Response) Clone() *DeleteLight_Response {
	c := &DeleteLight_Response{}
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *DeleteLight_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *DeleteLight_Response) SetDefaults() {
	t.Success = false
	t.StatusMessage = ""
}

// CloneDeleteLight_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneDeleteLight_ResponseSlice(dst, src []DeleteLight_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var DeleteLight_ResponseTypeSupport types.MessageTypeSupport = _DeleteLight_ResponseTypeSupport{}

type _DeleteLight_ResponseTypeSupport struct{}

func (t _DeleteLight_ResponseTypeSupport) New() types.Message {
	return NewDeleteLight_Response()
}

func (t _DeleteLight_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__DeleteLight_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__DeleteLight_Response__create())
}

func (t _DeleteLight_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__DeleteLight_Response__destroy((*C.gazebo_msgs__srv__DeleteLight_Response)(pointer_to_free))
}

func (t _DeleteLight_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*DeleteLight_Response)
	mem := (*C.gazebo_msgs__srv__DeleteLight_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _DeleteLight_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*DeleteLight_Response)
	mem := (*C.gazebo_msgs__srv__DeleteLight_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _DeleteLight_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__DeleteLight_Response())
}

type CDeleteLight_Response = C.gazebo_msgs__srv__DeleteLight_Response
type CDeleteLight_Response__Sequence = C.gazebo_msgs__srv__DeleteLight_Response__Sequence

func DeleteLight_Response__Sequence_to_Go(goSlice *[]DeleteLight_Response, cSlice CDeleteLight_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]DeleteLight_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__DeleteLight_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__DeleteLight_Response * uintptr(i)),
		))
		DeleteLight_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func DeleteLight_Response__Sequence_to_C(cSlice *CDeleteLight_Response__Sequence, goSlice []DeleteLight_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__DeleteLight_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__DeleteLight_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__DeleteLight_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__DeleteLight_Response * uintptr(i)),
		))
		DeleteLight_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func DeleteLight_Response__Array_to_Go(goSlice []DeleteLight_Response, cSlice []CDeleteLight_Response) {
	for i := 0; i < len(cSlice); i++ {
		DeleteLight_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func DeleteLight_Response__Array_to_C(cSlice []CDeleteLight_Response, goSlice []DeleteLight_Response) {
	for i := 0; i < len(goSlice); i++ {
		DeleteLight_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
