/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	gazebo_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/gazebo_msgs/msg"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_entity_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetEntityState_Response", GetEntityState_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetEntityState_Response
// function instead.
type GetEntityState_Response struct {
	Header std_msgs_msg.Header `yaml:"header"`// Standard metadata for higher-level stamped data types.. An entity can be a model, link, collision, light, etc.Be sure to use gazebo scoped naming notation (e.g. [model_name::link_name])Leaving empty or "world" will use inertial world frame.
	State gazebo_msgs_msg.EntityState `yaml:"state"`// Contains pose and twist.. An entity can be a model, link, collision, light, etc.Be sure to use gazebo scoped naming notation (e.g. [model_name::link_name])Leaving empty or "world" will use inertial world frame.* header.stamp Timestamp related to the pose.* header.frame_id Filled with the relative_frame.
	Success bool `yaml:"success"`// Return true if get was successful. If false, the state contains garbage.. An entity can be a model, link, collision, light, etc.Be sure to use gazebo scoped naming notation (e.g. [model_name::link_name])Leaving empty or "world" will use inertial world frame.* header.stamp Timestamp related to the pose.* header.frame_id Filled with the relative_frame.
}

// NewGetEntityState_Response creates a new GetEntityState_Response with default values.
func NewGetEntityState_Response() *GetEntityState_Response {
	self := GetEntityState_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetEntityState_Response) Clone() *GetEntityState_Response {
	c := &GetEntityState_Response{}
	c.Header = *t.Header.Clone()
	c.State = *t.State.Clone()
	c.Success = t.Success
	return c
}

func (t *GetEntityState_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetEntityState_Response) SetDefaults() {
	t.Header.SetDefaults()
	t.State.SetDefaults()
	t.Success = false
}

// CloneGetEntityState_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetEntityState_ResponseSlice(dst, src []GetEntityState_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetEntityState_ResponseTypeSupport types.MessageTypeSupport = _GetEntityState_ResponseTypeSupport{}

type _GetEntityState_ResponseTypeSupport struct{}

func (t _GetEntityState_ResponseTypeSupport) New() types.Message {
	return NewGetEntityState_Response()
}

func (t _GetEntityState_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetEntityState_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetEntityState_Response__create())
}

func (t _GetEntityState_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetEntityState_Response__destroy((*C.gazebo_msgs__srv__GetEntityState_Response)(pointer_to_free))
}

func (t _GetEntityState_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetEntityState_Response)
	mem := (*C.gazebo_msgs__srv__GetEntityState_Response)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	gazebo_msgs_msg.EntityStateTypeSupport.AsCStruct(unsafe.Pointer(&mem.state), &m.State)
	mem.success = C.bool(m.Success)
}

func (t _GetEntityState_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetEntityState_Response)
	mem := (*C.gazebo_msgs__srv__GetEntityState_Response)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	gazebo_msgs_msg.EntityStateTypeSupport.AsGoStruct(&m.State, unsafe.Pointer(&mem.state))
	m.Success = bool(mem.success)
}

func (t _GetEntityState_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetEntityState_Response())
}

type CGetEntityState_Response = C.gazebo_msgs__srv__GetEntityState_Response
type CGetEntityState_Response__Sequence = C.gazebo_msgs__srv__GetEntityState_Response__Sequence

func GetEntityState_Response__Sequence_to_Go(goSlice *[]GetEntityState_Response, cSlice CGetEntityState_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetEntityState_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetEntityState_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Response * uintptr(i)),
		))
		GetEntityState_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetEntityState_Response__Sequence_to_C(cSlice *CGetEntityState_Response__Sequence, goSlice []GetEntityState_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetEntityState_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetEntityState_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Response * uintptr(i)),
		))
		GetEntityState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetEntityState_Response__Array_to_Go(goSlice []GetEntityState_Response, cSlice []CGetEntityState_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetEntityState_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetEntityState_Response__Array_to_C(cSlice []CGetEntityState_Response, goSlice []GetEntityState_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetEntityState_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
