/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_entity_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetEntityState_Request", GetEntityState_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetEntityState_Request
// function instead.
type GetEntityState_Request struct {
	Name string `yaml:"name"`// Entity's scoped name.
	ReferenceFrame string `yaml:"reference_frame"`// Return pose and twist relative to this entity.. An entity can be a model, link, collision, light, etc.Be sure to use gazebo scoped naming notation (e.g. [model_name::link_name])
}

// NewGetEntityState_Request creates a new GetEntityState_Request with default values.
func NewGetEntityState_Request() *GetEntityState_Request {
	self := GetEntityState_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetEntityState_Request) Clone() *GetEntityState_Request {
	c := &GetEntityState_Request{}
	c.Name = t.Name
	c.ReferenceFrame = t.ReferenceFrame
	return c
}

func (t *GetEntityState_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetEntityState_Request) SetDefaults() {
	t.Name = ""
	t.ReferenceFrame = ""
}

// CloneGetEntityState_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetEntityState_RequestSlice(dst, src []GetEntityState_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetEntityState_RequestTypeSupport types.MessageTypeSupport = _GetEntityState_RequestTypeSupport{}

type _GetEntityState_RequestTypeSupport struct{}

func (t _GetEntityState_RequestTypeSupport) New() types.Message {
	return NewGetEntityState_Request()
}

func (t _GetEntityState_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetEntityState_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetEntityState_Request__create())
}

func (t _GetEntityState_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetEntityState_Request__destroy((*C.gazebo_msgs__srv__GetEntityState_Request)(pointer_to_free))
}

func (t _GetEntityState_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetEntityState_Request)
	mem := (*C.gazebo_msgs__srv__GetEntityState_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.name), m.Name)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.reference_frame), m.ReferenceFrame)
}

func (t _GetEntityState_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetEntityState_Request)
	mem := (*C.gazebo_msgs__srv__GetEntityState_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.Name, unsafe.Pointer(&mem.name))
	primitives.StringAsGoStruct(&m.ReferenceFrame, unsafe.Pointer(&mem.reference_frame))
}

func (t _GetEntityState_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetEntityState_Request())
}

type CGetEntityState_Request = C.gazebo_msgs__srv__GetEntityState_Request
type CGetEntityState_Request__Sequence = C.gazebo_msgs__srv__GetEntityState_Request__Sequence

func GetEntityState_Request__Sequence_to_Go(goSlice *[]GetEntityState_Request, cSlice CGetEntityState_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetEntityState_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetEntityState_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Request * uintptr(i)),
		))
		GetEntityState_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetEntityState_Request__Sequence_to_C(cSlice *CGetEntityState_Request__Sequence, goSlice []GetEntityState_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetEntityState_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetEntityState_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetEntityState_Request * uintptr(i)),
		))
		GetEntityState_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetEntityState_Request__Array_to_Go(goSlice []GetEntityState_Request, cSlice []CGetEntityState_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetEntityState_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetEntityState_Request__Array_to_C(cSlice []CGetEntityState_Request, goSlice []GetEntityState_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetEntityState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
