/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_joint_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetJointProperties_Response", GetJointProperties_ResponseTypeSupport)
}
const (
	GetJointProperties_Response_REVOLUTE uint8 = 0// single DOF. joint type
	GetJointProperties_Response_CONTINUOUS uint8 = 1// single DOF (revolute w/o limits). joint type
	GetJointProperties_Response_PRISMATIC uint8 = 2// single DOF. joint type
	GetJointProperties_Response_FIXED uint8 = 3// 0 DOF. joint type
	GetJointProperties_Response_BALL uint8 = 4// 3 DOF movement, 0 DOF control. joint type
	GetJointProperties_Response_UNIVERSAL uint8 = 5// 2 DOF. joint type
)

// Do not create instances of this type directly. Always use NewGetJointProperties_Response
// function instead.
type GetJointProperties_Response struct {
	Type uint8 `yaml:"type"`// joint type
	Damping []float64 `yaml:"damping"`// joint typedynamics properties
	Position []float64 `yaml:"position"`// joint typedynamics propertiesjoint state
	Rate []float64 `yaml:"rate"`// TODO(chapulina) Rename to velocity. joint typedynamics propertiesjoint state
	Success bool `yaml:"success"`// return true if get successful. joint typedynamics propertiesjoint stateservice return status
	StatusMessage string `yaml:"status_message"`// comments if available. joint typedynamics propertiesjoint stateservice return status
}

// NewGetJointProperties_Response creates a new GetJointProperties_Response with default values.
func NewGetJointProperties_Response() *GetJointProperties_Response {
	self := GetJointProperties_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetJointProperties_Response) Clone() *GetJointProperties_Response {
	c := &GetJointProperties_Response{}
	c.Type = t.Type
	if t.Damping != nil {
		c.Damping = make([]float64, len(t.Damping))
		copy(c.Damping, t.Damping)
	}
	if t.Position != nil {
		c.Position = make([]float64, len(t.Position))
		copy(c.Position, t.Position)
	}
	if t.Rate != nil {
		c.Rate = make([]float64, len(t.Rate))
		copy(c.Rate, t.Rate)
	}
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *GetJointProperties_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetJointProperties_Response) SetDefaults() {
	t.Type = 0
	t.Damping = nil
	t.Position = nil
	t.Rate = nil
	t.Success = false
	t.StatusMessage = ""
}

// CloneGetJointProperties_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetJointProperties_ResponseSlice(dst, src []GetJointProperties_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetJointProperties_ResponseTypeSupport types.MessageTypeSupport = _GetJointProperties_ResponseTypeSupport{}

type _GetJointProperties_ResponseTypeSupport struct{}

func (t _GetJointProperties_ResponseTypeSupport) New() types.Message {
	return NewGetJointProperties_Response()
}

func (t _GetJointProperties_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetJointProperties_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetJointProperties_Response__create())
}

func (t _GetJointProperties_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetJointProperties_Response__destroy((*C.gazebo_msgs__srv__GetJointProperties_Response)(pointer_to_free))
}

func (t _GetJointProperties_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetJointProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetJointProperties_Response)(dst)
	mem._type = C.uint8_t(m.Type)
	primitives.Float64__Sequence_to_C((*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.damping)), m.Damping)
	primitives.Float64__Sequence_to_C((*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.position)), m.Position)
	primitives.Float64__Sequence_to_C((*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.rate)), m.Rate)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _GetJointProperties_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetJointProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetJointProperties_Response)(ros2_message_buffer)
	m.Type = uint8(mem._type)
	primitives.Float64__Sequence_to_Go(&m.Damping, *(*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.damping)))
	primitives.Float64__Sequence_to_Go(&m.Position, *(*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.position)))
	primitives.Float64__Sequence_to_Go(&m.Rate, *(*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.rate)))
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _GetJointProperties_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetJointProperties_Response())
}

type CGetJointProperties_Response = C.gazebo_msgs__srv__GetJointProperties_Response
type CGetJointProperties_Response__Sequence = C.gazebo_msgs__srv__GetJointProperties_Response__Sequence

func GetJointProperties_Response__Sequence_to_Go(goSlice *[]GetJointProperties_Response, cSlice CGetJointProperties_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetJointProperties_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetJointProperties_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetJointProperties_Response * uintptr(i)),
		))
		GetJointProperties_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetJointProperties_Response__Sequence_to_C(cSlice *CGetJointProperties_Response__Sequence, goSlice []GetJointProperties_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetJointProperties_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetJointProperties_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetJointProperties_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetJointProperties_Response * uintptr(i)),
		))
		GetJointProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetJointProperties_Response__Array_to_Go(goSlice []GetJointProperties_Response, cSlice []CGetJointProperties_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetJointProperties_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetJointProperties_Response__Array_to_C(cSlice []CGetJointProperties_Response, goSlice []GetJointProperties_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetJointProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
