/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_light_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetLightProperties_Response", GetLightProperties_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetLightProperties_Response
// function instead.
type GetLightProperties_Response struct {
	Diffuse std_msgs_msg.ColorRGBA `yaml:"diffuse"`// diffuse color as red, green, blue, alpha
	AttenuationConstant float64 `yaml:"attenuation_constant"`
	AttenuationLinear float64 `yaml:"attenuation_linear"`
	AttenuationQuadratic float64 `yaml:"attenuation_quadratic"`
	Success bool `yaml:"success"`// return true if get successful
	StatusMessage string `yaml:"status_message"`// comments if available
}

// NewGetLightProperties_Response creates a new GetLightProperties_Response with default values.
func NewGetLightProperties_Response() *GetLightProperties_Response {
	self := GetLightProperties_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetLightProperties_Response) Clone() *GetLightProperties_Response {
	c := &GetLightProperties_Response{}
	c.Diffuse = *t.Diffuse.Clone()
	c.AttenuationConstant = t.AttenuationConstant
	c.AttenuationLinear = t.AttenuationLinear
	c.AttenuationQuadratic = t.AttenuationQuadratic
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *GetLightProperties_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetLightProperties_Response) SetDefaults() {
	t.Diffuse.SetDefaults()
	t.AttenuationConstant = 0
	t.AttenuationLinear = 0
	t.AttenuationQuadratic = 0
	t.Success = false
	t.StatusMessage = ""
}

// CloneGetLightProperties_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetLightProperties_ResponseSlice(dst, src []GetLightProperties_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetLightProperties_ResponseTypeSupport types.MessageTypeSupport = _GetLightProperties_ResponseTypeSupport{}

type _GetLightProperties_ResponseTypeSupport struct{}

func (t _GetLightProperties_ResponseTypeSupport) New() types.Message {
	return NewGetLightProperties_Response()
}

func (t _GetLightProperties_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetLightProperties_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetLightProperties_Response__create())
}

func (t _GetLightProperties_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetLightProperties_Response__destroy((*C.gazebo_msgs__srv__GetLightProperties_Response)(pointer_to_free))
}

func (t _GetLightProperties_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetLightProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetLightProperties_Response)(dst)
	std_msgs_msg.ColorRGBATypeSupport.AsCStruct(unsafe.Pointer(&mem.diffuse), &m.Diffuse)
	mem.attenuation_constant = C.double(m.AttenuationConstant)
	mem.attenuation_linear = C.double(m.AttenuationLinear)
	mem.attenuation_quadratic = C.double(m.AttenuationQuadratic)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _GetLightProperties_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetLightProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetLightProperties_Response)(ros2_message_buffer)
	std_msgs_msg.ColorRGBATypeSupport.AsGoStruct(&m.Diffuse, unsafe.Pointer(&mem.diffuse))
	m.AttenuationConstant = float64(mem.attenuation_constant)
	m.AttenuationLinear = float64(mem.attenuation_linear)
	m.AttenuationQuadratic = float64(mem.attenuation_quadratic)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _GetLightProperties_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetLightProperties_Response())
}

type CGetLightProperties_Response = C.gazebo_msgs__srv__GetLightProperties_Response
type CGetLightProperties_Response__Sequence = C.gazebo_msgs__srv__GetLightProperties_Response__Sequence

func GetLightProperties_Response__Sequence_to_Go(goSlice *[]GetLightProperties_Response, cSlice CGetLightProperties_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetLightProperties_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetLightProperties_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Response * uintptr(i)),
		))
		GetLightProperties_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetLightProperties_Response__Sequence_to_C(cSlice *CGetLightProperties_Response__Sequence, goSlice []GetLightProperties_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetLightProperties_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetLightProperties_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Response * uintptr(i)),
		))
		GetLightProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetLightProperties_Response__Array_to_Go(goSlice []GetLightProperties_Response, cSlice []CGetLightProperties_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetLightProperties_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetLightProperties_Response__Array_to_C(cSlice []CGetLightProperties_Response, goSlice []GetLightProperties_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetLightProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
