/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_light_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetLightProperties_Request", GetLightProperties_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetLightProperties_Request
// function instead.
type GetLightProperties_Request struct {
	LightName string `yaml:"light_name"`// name of Gazebo Light
}

// NewGetLightProperties_Request creates a new GetLightProperties_Request with default values.
func NewGetLightProperties_Request() *GetLightProperties_Request {
	self := GetLightProperties_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetLightProperties_Request) Clone() *GetLightProperties_Request {
	c := &GetLightProperties_Request{}
	c.LightName = t.LightName
	return c
}

func (t *GetLightProperties_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetLightProperties_Request) SetDefaults() {
	t.LightName = ""
}

// CloneGetLightProperties_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetLightProperties_RequestSlice(dst, src []GetLightProperties_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetLightProperties_RequestTypeSupport types.MessageTypeSupport = _GetLightProperties_RequestTypeSupport{}

type _GetLightProperties_RequestTypeSupport struct{}

func (t _GetLightProperties_RequestTypeSupport) New() types.Message {
	return NewGetLightProperties_Request()
}

func (t _GetLightProperties_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetLightProperties_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetLightProperties_Request__create())
}

func (t _GetLightProperties_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetLightProperties_Request__destroy((*C.gazebo_msgs__srv__GetLightProperties_Request)(pointer_to_free))
}

func (t _GetLightProperties_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetLightProperties_Request)
	mem := (*C.gazebo_msgs__srv__GetLightProperties_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.light_name), m.LightName)
}

func (t _GetLightProperties_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetLightProperties_Request)
	mem := (*C.gazebo_msgs__srv__GetLightProperties_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.LightName, unsafe.Pointer(&mem.light_name))
}

func (t _GetLightProperties_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetLightProperties_Request())
}

type CGetLightProperties_Request = C.gazebo_msgs__srv__GetLightProperties_Request
type CGetLightProperties_Request__Sequence = C.gazebo_msgs__srv__GetLightProperties_Request__Sequence

func GetLightProperties_Request__Sequence_to_Go(goSlice *[]GetLightProperties_Request, cSlice CGetLightProperties_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetLightProperties_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetLightProperties_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Request * uintptr(i)),
		))
		GetLightProperties_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetLightProperties_Request__Sequence_to_C(cSlice *CGetLightProperties_Request__Sequence, goSlice []GetLightProperties_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetLightProperties_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetLightProperties_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetLightProperties_Request * uintptr(i)),
		))
		GetLightProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetLightProperties_Request__Array_to_Go(goSlice []GetLightProperties_Request, cSlice []CGetLightProperties_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetLightProperties_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetLightProperties_Request__Array_to_C(cSlice []CGetLightProperties_Request, goSlice []GetLightProperties_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetLightProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
