/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_model_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetModelState_Request", GetModelState_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetModelState_Request
// function instead.
type GetModelState_Request struct {
	ModelName string `yaml:"model_name"`// name of Gazebo Model. Deprecated, kept for ROS 1 bridge.Use GetEntityState
	RelativeEntityName string `yaml:"relative_entity_name"`// return pose and twist relative to this entity. Deprecated, kept for ROS 1 bridge.Use GetEntityState
}

// NewGetModelState_Request creates a new GetModelState_Request with default values.
func NewGetModelState_Request() *GetModelState_Request {
	self := GetModelState_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetModelState_Request) Clone() *GetModelState_Request {
	c := &GetModelState_Request{}
	c.ModelName = t.ModelName
	c.RelativeEntityName = t.RelativeEntityName
	return c
}

func (t *GetModelState_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetModelState_Request) SetDefaults() {
	t.ModelName = ""
	t.RelativeEntityName = ""
}

// CloneGetModelState_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetModelState_RequestSlice(dst, src []GetModelState_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetModelState_RequestTypeSupport types.MessageTypeSupport = _GetModelState_RequestTypeSupport{}

type _GetModelState_RequestTypeSupport struct{}

func (t _GetModelState_RequestTypeSupport) New() types.Message {
	return NewGetModelState_Request()
}

func (t _GetModelState_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetModelState_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetModelState_Request__create())
}

func (t _GetModelState_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetModelState_Request__destroy((*C.gazebo_msgs__srv__GetModelState_Request)(pointer_to_free))
}

func (t _GetModelState_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetModelState_Request)
	mem := (*C.gazebo_msgs__srv__GetModelState_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.model_name), m.ModelName)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.relative_entity_name), m.RelativeEntityName)
}

func (t _GetModelState_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetModelState_Request)
	mem := (*C.gazebo_msgs__srv__GetModelState_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ModelName, unsafe.Pointer(&mem.model_name))
	primitives.StringAsGoStruct(&m.RelativeEntityName, unsafe.Pointer(&mem.relative_entity_name))
}

func (t _GetModelState_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetModelState_Request())
}

type CGetModelState_Request = C.gazebo_msgs__srv__GetModelState_Request
type CGetModelState_Request__Sequence = C.gazebo_msgs__srv__GetModelState_Request__Sequence

func GetModelState_Request__Sequence_to_Go(goSlice *[]GetModelState_Request, cSlice CGetModelState_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetModelState_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetModelState_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelState_Request * uintptr(i)),
		))
		GetModelState_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetModelState_Request__Sequence_to_C(cSlice *CGetModelState_Request__Sequence, goSlice []GetModelState_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetModelState_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetModelState_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetModelState_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelState_Request * uintptr(i)),
		))
		GetModelState_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetModelState_Request__Array_to_Go(goSlice []GetModelState_Request, cSlice []CGetModelState_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetModelState_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetModelState_Request__Array_to_C(cSlice []CGetModelState_Request, goSlice []GetModelState_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetModelState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
