/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_model_list.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetModelList_Request", GetModelList_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetModelList_Request
// function instead.
type GetModelList_Request struct {
}

// NewGetModelList_Request creates a new GetModelList_Request with default values.
func NewGetModelList_Request() *GetModelList_Request {
	self := GetModelList_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetModelList_Request) Clone() *GetModelList_Request {
	c := &GetModelList_Request{}
	return c
}

func (t *GetModelList_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetModelList_Request) SetDefaults() {
}

// CloneGetModelList_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetModelList_RequestSlice(dst, src []GetModelList_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetModelList_RequestTypeSupport types.MessageTypeSupport = _GetModelList_RequestTypeSupport{}

type _GetModelList_RequestTypeSupport struct{}

func (t _GetModelList_RequestTypeSupport) New() types.Message {
	return NewGetModelList_Request()
}

func (t _GetModelList_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetModelList_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetModelList_Request__create())
}

func (t _GetModelList_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetModelList_Request__destroy((*C.gazebo_msgs__srv__GetModelList_Request)(pointer_to_free))
}

func (t _GetModelList_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetModelList_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetModelList_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetModelList_Request())
}

type CGetModelList_Request = C.gazebo_msgs__srv__GetModelList_Request
type CGetModelList_Request__Sequence = C.gazebo_msgs__srv__GetModelList_Request__Sequence

func GetModelList_Request__Sequence_to_Go(goSlice *[]GetModelList_Request, cSlice CGetModelList_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetModelList_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetModelList_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelList_Request * uintptr(i)),
		))
		GetModelList_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetModelList_Request__Sequence_to_C(cSlice *CGetModelList_Request__Sequence, goSlice []GetModelList_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetModelList_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetModelList_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetModelList_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelList_Request * uintptr(i)),
		))
		GetModelList_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetModelList_Request__Array_to_Go(goSlice []GetModelList_Request, cSlice []CGetModelList_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetModelList_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetModelList_Request__Array_to_C(cSlice []CGetModelList_Request, goSlice []GetModelList_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetModelList_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
