/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	std_msgs_msg "github.com/mehmetkillioglu/rclgo-msgs/std_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lstd_msgs__rosidl_typesupport_c -lstd_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_model_list.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetModelList_Response", GetModelList_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetModelList_Response
// function instead.
type GetModelList_Response struct {
	Header std_msgs_msg.Header `yaml:"header"`// Standard metadata for higher-level stamped data types.
	ModelNames []string `yaml:"model_names"`// list of models in the world. * header.stamp Simulation time when data was collected.
	Success bool `yaml:"success"`// return true if get successful. * header.stamp Simulation time when data was collected.
}

// NewGetModelList_Response creates a new GetModelList_Response with default values.
func NewGetModelList_Response() *GetModelList_Response {
	self := GetModelList_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetModelList_Response) Clone() *GetModelList_Response {
	c := &GetModelList_Response{}
	c.Header = *t.Header.Clone()
	if t.ModelNames != nil {
		c.ModelNames = make([]string, len(t.ModelNames))
		copy(c.ModelNames, t.ModelNames)
	}
	c.Success = t.Success
	return c
}

func (t *GetModelList_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetModelList_Response) SetDefaults() {
	t.Header.SetDefaults()
	t.ModelNames = nil
	t.Success = false
}

// CloneGetModelList_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetModelList_ResponseSlice(dst, src []GetModelList_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetModelList_ResponseTypeSupport types.MessageTypeSupport = _GetModelList_ResponseTypeSupport{}

type _GetModelList_ResponseTypeSupport struct{}

func (t _GetModelList_ResponseTypeSupport) New() types.Message {
	return NewGetModelList_Response()
}

func (t _GetModelList_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetModelList_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetModelList_Response__create())
}

func (t _GetModelList_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetModelList_Response__destroy((*C.gazebo_msgs__srv__GetModelList_Response)(pointer_to_free))
}

func (t _GetModelList_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetModelList_Response)
	mem := (*C.gazebo_msgs__srv__GetModelList_Response)(dst)
	std_msgs_msg.HeaderTypeSupport.AsCStruct(unsafe.Pointer(&mem.header), &m.Header)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.model_names)), m.ModelNames)
	mem.success = C.bool(m.Success)
}

func (t _GetModelList_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetModelList_Response)
	mem := (*C.gazebo_msgs__srv__GetModelList_Response)(ros2_message_buffer)
	std_msgs_msg.HeaderTypeSupport.AsGoStruct(&m.Header, unsafe.Pointer(&mem.header))
	primitives.String__Sequence_to_Go(&m.ModelNames, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.model_names)))
	m.Success = bool(mem.success)
}

func (t _GetModelList_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetModelList_Response())
}

type CGetModelList_Response = C.gazebo_msgs__srv__GetModelList_Response
type CGetModelList_Response__Sequence = C.gazebo_msgs__srv__GetModelList_Response__Sequence

func GetModelList_Response__Sequence_to_Go(goSlice *[]GetModelList_Response, cSlice CGetModelList_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetModelList_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetModelList_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelList_Response * uintptr(i)),
		))
		GetModelList_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetModelList_Response__Sequence_to_C(cSlice *CGetModelList_Response__Sequence, goSlice []GetModelList_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetModelList_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetModelList_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetModelList_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetModelList_Response * uintptr(i)),
		))
		GetModelList_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetModelList_Response__Array_to_Go(goSlice []GetModelList_Response, cSlice []CGetModelList_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetModelList_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetModelList_Response__Array_to_C(cSlice []CGetModelList_Response, goSlice []GetModelList_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetModelList_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
