/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	gazebo_msgs_msg "github.com/tiiuae/rclgo-msgs/gazebo_msgs/msg"
	geometry_msgs_msg "github.com/tiiuae/rclgo-msgs/geometry_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_physics_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetPhysicsProperties_Response", GetPhysicsProperties_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetPhysicsProperties_Response
// function instead.
type GetPhysicsProperties_Response struct {
	TimeStep float64 `yaml:"time_step"`// dt in seconds. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	Pause bool `yaml:"pause"`// true if physics engine is paused. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	MaxUpdateRate float64 `yaml:"max_update_rate"`// throttle maximum physics update rate. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	Gravity geometry_msgs_msg.Vector3 `yaml:"gravity"`// gravity vector (e.g. earth ~[0,0,-9.81]). sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	OdeConfig gazebo_msgs_msg.ODEPhysics `yaml:"ode_config"`// contains physics configurations pertaining to ODE. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	Success bool `yaml:"success"`// return true if set wrench successful. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	StatusMessage string `yaml:"status_message"`// comments if available. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
}

// NewGetPhysicsProperties_Response creates a new GetPhysicsProperties_Response with default values.
func NewGetPhysicsProperties_Response() *GetPhysicsProperties_Response {
	self := GetPhysicsProperties_Response{}
	self.SetDefaults()
	return &self
}

func (t *GetPhysicsProperties_Response) Clone() *GetPhysicsProperties_Response {
	c := &GetPhysicsProperties_Response{}
	c.TimeStep = t.TimeStep
	c.Pause = t.Pause
	c.MaxUpdateRate = t.MaxUpdateRate
	c.Gravity = *t.Gravity.Clone()
	c.OdeConfig = *t.OdeConfig.Clone()
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *GetPhysicsProperties_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetPhysicsProperties_Response) SetDefaults() {
	t.TimeStep = 0
	t.Pause = false
	t.MaxUpdateRate = 0
	t.Gravity.SetDefaults()
	t.OdeConfig.SetDefaults()
	t.Success = false
	t.StatusMessage = ""
}

// CloneGetPhysicsProperties_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetPhysicsProperties_ResponseSlice(dst, src []GetPhysicsProperties_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetPhysicsProperties_ResponseTypeSupport types.MessageTypeSupport = _GetPhysicsProperties_ResponseTypeSupport{}

type _GetPhysicsProperties_ResponseTypeSupport struct{}

func (t _GetPhysicsProperties_ResponseTypeSupport) New() types.Message {
	return NewGetPhysicsProperties_Response()
}

func (t _GetPhysicsProperties_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetPhysicsProperties_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetPhysicsProperties_Response__create())
}

func (t _GetPhysicsProperties_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetPhysicsProperties_Response__destroy((*C.gazebo_msgs__srv__GetPhysicsProperties_Response)(pointer_to_free))
}

func (t _GetPhysicsProperties_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*GetPhysicsProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetPhysicsProperties_Response)(dst)
	mem.time_step = C.double(m.TimeStep)
	mem.pause = C.bool(m.Pause)
	mem.max_update_rate = C.double(m.MaxUpdateRate)
	geometry_msgs_msg.Vector3TypeSupport.AsCStruct(unsafe.Pointer(&mem.gravity), &m.Gravity)
	gazebo_msgs_msg.ODEPhysicsTypeSupport.AsCStruct(unsafe.Pointer(&mem.ode_config), &m.OdeConfig)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _GetPhysicsProperties_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*GetPhysicsProperties_Response)
	mem := (*C.gazebo_msgs__srv__GetPhysicsProperties_Response)(ros2_message_buffer)
	m.TimeStep = float64(mem.time_step)
	m.Pause = bool(mem.pause)
	m.MaxUpdateRate = float64(mem.max_update_rate)
	geometry_msgs_msg.Vector3TypeSupport.AsGoStruct(&m.Gravity, unsafe.Pointer(&mem.gravity))
	gazebo_msgs_msg.ODEPhysicsTypeSupport.AsGoStruct(&m.OdeConfig, unsafe.Pointer(&mem.ode_config))
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _GetPhysicsProperties_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetPhysicsProperties_Response())
}

type CGetPhysicsProperties_Response = C.gazebo_msgs__srv__GetPhysicsProperties_Response
type CGetPhysicsProperties_Response__Sequence = C.gazebo_msgs__srv__GetPhysicsProperties_Response__Sequence

func GetPhysicsProperties_Response__Sequence_to_Go(goSlice *[]GetPhysicsProperties_Response, cSlice CGetPhysicsProperties_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetPhysicsProperties_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetPhysicsProperties_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetPhysicsProperties_Response * uintptr(i)),
		))
		GetPhysicsProperties_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetPhysicsProperties_Response__Sequence_to_C(cSlice *CGetPhysicsProperties_Response__Sequence, goSlice []GetPhysicsProperties_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetPhysicsProperties_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetPhysicsProperties_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetPhysicsProperties_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetPhysicsProperties_Response * uintptr(i)),
		))
		GetPhysicsProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetPhysicsProperties_Response__Array_to_Go(goSlice []GetPhysicsProperties_Response, cSlice []CGetPhysicsProperties_Response) {
	for i := 0; i < len(cSlice); i++ {
		GetPhysicsProperties_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetPhysicsProperties_Response__Array_to_C(cSlice []CGetPhysicsProperties_Response, goSlice []GetPhysicsProperties_Response) {
	for i := 0; i < len(goSlice); i++ {
		GetPhysicsProperties_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
