/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/get_world_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/GetWorldProperties_Request", GetWorldProperties_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewGetWorldProperties_Request
// function instead.
type GetWorldProperties_Request struct {
}

// NewGetWorldProperties_Request creates a new GetWorldProperties_Request with default values.
func NewGetWorldProperties_Request() *GetWorldProperties_Request {
	self := GetWorldProperties_Request{}
	self.SetDefaults()
	return &self
}

func (t *GetWorldProperties_Request) Clone() *GetWorldProperties_Request {
	c := &GetWorldProperties_Request{}
	return c
}

func (t *GetWorldProperties_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *GetWorldProperties_Request) SetDefaults() {
}

// CloneGetWorldProperties_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneGetWorldProperties_RequestSlice(dst, src []GetWorldProperties_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var GetWorldProperties_RequestTypeSupport types.MessageTypeSupport = _GetWorldProperties_RequestTypeSupport{}

type _GetWorldProperties_RequestTypeSupport struct{}

func (t _GetWorldProperties_RequestTypeSupport) New() types.Message {
	return NewGetWorldProperties_Request()
}

func (t _GetWorldProperties_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__GetWorldProperties_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__GetWorldProperties_Request__create())
}

func (t _GetWorldProperties_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__GetWorldProperties_Request__destroy((*C.gazebo_msgs__srv__GetWorldProperties_Request)(pointer_to_free))
}

func (t _GetWorldProperties_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _GetWorldProperties_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _GetWorldProperties_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__GetWorldProperties_Request())
}

type CGetWorldProperties_Request = C.gazebo_msgs__srv__GetWorldProperties_Request
type CGetWorldProperties_Request__Sequence = C.gazebo_msgs__srv__GetWorldProperties_Request__Sequence

func GetWorldProperties_Request__Sequence_to_Go(goSlice *[]GetWorldProperties_Request, cSlice CGetWorldProperties_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]GetWorldProperties_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__GetWorldProperties_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetWorldProperties_Request * uintptr(i)),
		))
		GetWorldProperties_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func GetWorldProperties_Request__Sequence_to_C(cSlice *CGetWorldProperties_Request__Sequence, goSlice []GetWorldProperties_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__GetWorldProperties_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__GetWorldProperties_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__GetWorldProperties_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__GetWorldProperties_Request * uintptr(i)),
		))
		GetWorldProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func GetWorldProperties_Request__Array_to_Go(goSlice []GetWorldProperties_Request, cSlice []CGetWorldProperties_Request) {
	for i := 0; i < len(cSlice); i++ {
		GetWorldProperties_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func GetWorldProperties_Request__Array_to_C(cSlice []CGetWorldProperties_Request, goSlice []GetWorldProperties_Request) {
	for i := 0; i < len(goSlice); i++ {
		GetWorldProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
