/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/joint_request.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/JointRequest_Response", JointRequest_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewJointRequest_Response
// function instead.
type JointRequest_Response struct {
}

// NewJointRequest_Response creates a new JointRequest_Response with default values.
func NewJointRequest_Response() *JointRequest_Response {
	self := JointRequest_Response{}
	self.SetDefaults()
	return &self
}

func (t *JointRequest_Response) Clone() *JointRequest_Response {
	c := &JointRequest_Response{}
	return c
}

func (t *JointRequest_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *JointRequest_Response) SetDefaults() {
}

// CloneJointRequest_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneJointRequest_ResponseSlice(dst, src []JointRequest_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var JointRequest_ResponseTypeSupport types.MessageTypeSupport = _JointRequest_ResponseTypeSupport{}

type _JointRequest_ResponseTypeSupport struct{}

func (t _JointRequest_ResponseTypeSupport) New() types.Message {
	return NewJointRequest_Response()
}

func (t _JointRequest_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__JointRequest_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__JointRequest_Response__create())
}

func (t _JointRequest_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__JointRequest_Response__destroy((*C.gazebo_msgs__srv__JointRequest_Response)(pointer_to_free))
}

func (t _JointRequest_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	
}

func (t _JointRequest_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	
}

func (t _JointRequest_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__JointRequest_Response())
}

type CJointRequest_Response = C.gazebo_msgs__srv__JointRequest_Response
type CJointRequest_Response__Sequence = C.gazebo_msgs__srv__JointRequest_Response__Sequence

func JointRequest_Response__Sequence_to_Go(goSlice *[]JointRequest_Response, cSlice CJointRequest_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]JointRequest_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__JointRequest_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__JointRequest_Response * uintptr(i)),
		))
		JointRequest_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func JointRequest_Response__Sequence_to_C(cSlice *CJointRequest_Response__Sequence, goSlice []JointRequest_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__JointRequest_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__JointRequest_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__JointRequest_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__JointRequest_Response * uintptr(i)),
		))
		JointRequest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func JointRequest_Response__Array_to_Go(goSlice []JointRequest_Response, cSlice []CJointRequest_Response) {
	for i := 0; i < len(cSlice); i++ {
		JointRequest_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func JointRequest_Response__Array_to_C(cSlice []CJointRequest_Response, goSlice []JointRequest_Response) {
	for i := 0; i < len(goSlice); i++ {
		JointRequest_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
