/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/joint_request.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/JointRequest_Request", JointRequest_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewJointRequest_Request
// function instead.
type JointRequest_Request struct {
	JointName string `yaml:"joint_name"`// name of the joint requested
}

// NewJointRequest_Request creates a new JointRequest_Request with default values.
func NewJointRequest_Request() *JointRequest_Request {
	self := JointRequest_Request{}
	self.SetDefaults()
	return &self
}

func (t *JointRequest_Request) Clone() *JointRequest_Request {
	c := &JointRequest_Request{}
	c.JointName = t.JointName
	return c
}

func (t *JointRequest_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *JointRequest_Request) SetDefaults() {
	t.JointName = ""
}

// CloneJointRequest_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneJointRequest_RequestSlice(dst, src []JointRequest_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var JointRequest_RequestTypeSupport types.MessageTypeSupport = _JointRequest_RequestTypeSupport{}

type _JointRequest_RequestTypeSupport struct{}

func (t _JointRequest_RequestTypeSupport) New() types.Message {
	return NewJointRequest_Request()
}

func (t _JointRequest_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__JointRequest_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__JointRequest_Request__create())
}

func (t _JointRequest_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__JointRequest_Request__destroy((*C.gazebo_msgs__srv__JointRequest_Request)(pointer_to_free))
}

func (t _JointRequest_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*JointRequest_Request)
	mem := (*C.gazebo_msgs__srv__JointRequest_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.joint_name), m.JointName)
}

func (t _JointRequest_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*JointRequest_Request)
	mem := (*C.gazebo_msgs__srv__JointRequest_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.JointName, unsafe.Pointer(&mem.joint_name))
}

func (t _JointRequest_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__JointRequest_Request())
}

type CJointRequest_Request = C.gazebo_msgs__srv__JointRequest_Request
type CJointRequest_Request__Sequence = C.gazebo_msgs__srv__JointRequest_Request__Sequence

func JointRequest_Request__Sequence_to_Go(goSlice *[]JointRequest_Request, cSlice CJointRequest_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]JointRequest_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__JointRequest_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__JointRequest_Request * uintptr(i)),
		))
		JointRequest_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func JointRequest_Request__Sequence_to_C(cSlice *CJointRequest_Request__Sequence, goSlice []JointRequest_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__JointRequest_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__JointRequest_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__JointRequest_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__JointRequest_Request * uintptr(i)),
		))
		JointRequest_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func JointRequest_Request__Array_to_Go(goSlice []JointRequest_Request, cSlice []CJointRequest_Request) {
	for i := 0; i < len(cSlice); i++ {
		JointRequest_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func JointRequest_Request__Array_to_C(cSlice []CJointRequest_Request, goSlice []JointRequest_Request) {
	for i := 0; i < len(goSlice); i++ {
		JointRequest_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
