/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "github.com/tiiuae/rclgo-msgs/geometry_msgs/msg"
	trajectory_msgs_msg "github.com/tiiuae/rclgo-msgs/trajectory_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c
#cgo LDFLAGS: -ltrajectory_msgs__rosidl_typesupport_c -ltrajectory_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/set_joint_trajectory.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SetJointTrajectory_Request", SetJointTrajectory_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSetJointTrajectory_Request
// function instead.
type SetJointTrajectory_Request struct {
	ModelName string `yaml:"model_name"`// Deprecated, kept for ROS 1 bridge.
	JointTrajectory trajectory_msgs_msg.JointTrajectory `yaml:"joint_trajectory"`// Deprecated, kept for ROS 1 bridge.
	ModelPose geometry_msgs_msg.Pose `yaml:"model_pose"`// Deprecated, kept for ROS 1 bridge.
	SetModelPose bool `yaml:"set_model_pose"`// Deprecated, kept for ROS 1 bridge.
	DisablePhysicsUpdates bool `yaml:"disable_physics_updates"`// defaults to false. Deprecated, kept for ROS 1 bridge.
}

// NewSetJointTrajectory_Request creates a new SetJointTrajectory_Request with default values.
func NewSetJointTrajectory_Request() *SetJointTrajectory_Request {
	self := SetJointTrajectory_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetJointTrajectory_Request) Clone() *SetJointTrajectory_Request {
	c := &SetJointTrajectory_Request{}
	c.ModelName = t.ModelName
	c.JointTrajectory = *t.JointTrajectory.Clone()
	c.ModelPose = *t.ModelPose.Clone()
	c.SetModelPose = t.SetModelPose
	c.DisablePhysicsUpdates = t.DisablePhysicsUpdates
	return c
}

func (t *SetJointTrajectory_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetJointTrajectory_Request) SetDefaults() {
	t.ModelName = ""
	t.JointTrajectory.SetDefaults()
	t.ModelPose.SetDefaults()
	t.SetModelPose = false
	t.DisablePhysicsUpdates = false
}

// CloneSetJointTrajectory_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetJointTrajectory_RequestSlice(dst, src []SetJointTrajectory_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetJointTrajectory_RequestTypeSupport types.MessageTypeSupport = _SetJointTrajectory_RequestTypeSupport{}

type _SetJointTrajectory_RequestTypeSupport struct{}

func (t _SetJointTrajectory_RequestTypeSupport) New() types.Message {
	return NewSetJointTrajectory_Request()
}

func (t _SetJointTrajectory_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SetJointTrajectory_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SetJointTrajectory_Request__create())
}

func (t _SetJointTrajectory_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SetJointTrajectory_Request__destroy((*C.gazebo_msgs__srv__SetJointTrajectory_Request)(pointer_to_free))
}

func (t _SetJointTrajectory_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetJointTrajectory_Request)
	mem := (*C.gazebo_msgs__srv__SetJointTrajectory_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.model_name), m.ModelName)
	trajectory_msgs_msg.JointTrajectoryTypeSupport.AsCStruct(unsafe.Pointer(&mem.joint_trajectory), &m.JointTrajectory)
	geometry_msgs_msg.PoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.model_pose), &m.ModelPose)
	mem.set_model_pose = C.bool(m.SetModelPose)
	mem.disable_physics_updates = C.bool(m.DisablePhysicsUpdates)
}

func (t _SetJointTrajectory_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetJointTrajectory_Request)
	mem := (*C.gazebo_msgs__srv__SetJointTrajectory_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ModelName, unsafe.Pointer(&mem.model_name))
	trajectory_msgs_msg.JointTrajectoryTypeSupport.AsGoStruct(&m.JointTrajectory, unsafe.Pointer(&mem.joint_trajectory))
	geometry_msgs_msg.PoseTypeSupport.AsGoStruct(&m.ModelPose, unsafe.Pointer(&mem.model_pose))
	m.SetModelPose = bool(mem.set_model_pose)
	m.DisablePhysicsUpdates = bool(mem.disable_physics_updates)
}

func (t _SetJointTrajectory_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SetJointTrajectory_Request())
}

type CSetJointTrajectory_Request = C.gazebo_msgs__srv__SetJointTrajectory_Request
type CSetJointTrajectory_Request__Sequence = C.gazebo_msgs__srv__SetJointTrajectory_Request__Sequence

func SetJointTrajectory_Request__Sequence_to_Go(goSlice *[]SetJointTrajectory_Request, cSlice CSetJointTrajectory_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetJointTrajectory_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SetJointTrajectory_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetJointTrajectory_Request * uintptr(i)),
		))
		SetJointTrajectory_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SetJointTrajectory_Request__Sequence_to_C(cSlice *CSetJointTrajectory_Request__Sequence, goSlice []SetJointTrajectory_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SetJointTrajectory_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SetJointTrajectory_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SetJointTrajectory_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetJointTrajectory_Request * uintptr(i)),
		))
		SetJointTrajectory_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SetJointTrajectory_Request__Array_to_Go(goSlice []SetJointTrajectory_Request, cSlice []CSetJointTrajectory_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetJointTrajectory_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetJointTrajectory_Request__Array_to_C(cSlice []CSetJointTrajectory_Request, goSlice []SetJointTrajectory_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetJointTrajectory_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
