/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/set_model_configuration.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SetModelConfiguration_Request", SetModelConfiguration_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSetModelConfiguration_Request
// function instead.
type SetModelConfiguration_Request struct {
	ModelName string `yaml:"model_name"`// model to set state. Set joint positions for a model
	UrdfParamName string `yaml:"urdf_param_name"`// UNUSED. Set joint positions for a model
	JointNames []string `yaml:"joint_names"`// list of joints to set positions.  if joint is not listed here, preserve current position.
	JointPositions []float64 `yaml:"joint_positions"`// set to this position.
}

// NewSetModelConfiguration_Request creates a new SetModelConfiguration_Request with default values.
func NewSetModelConfiguration_Request() *SetModelConfiguration_Request {
	self := SetModelConfiguration_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetModelConfiguration_Request) Clone() *SetModelConfiguration_Request {
	c := &SetModelConfiguration_Request{}
	c.ModelName = t.ModelName
	c.UrdfParamName = t.UrdfParamName
	if t.JointNames != nil {
		c.JointNames = make([]string, len(t.JointNames))
		copy(c.JointNames, t.JointNames)
	}
	if t.JointPositions != nil {
		c.JointPositions = make([]float64, len(t.JointPositions))
		copy(c.JointPositions, t.JointPositions)
	}
	return c
}

func (t *SetModelConfiguration_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetModelConfiguration_Request) SetDefaults() {
	t.ModelName = ""
	t.UrdfParamName = ""
	t.JointNames = nil
	t.JointPositions = nil
}

// CloneSetModelConfiguration_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetModelConfiguration_RequestSlice(dst, src []SetModelConfiguration_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetModelConfiguration_RequestTypeSupport types.MessageTypeSupport = _SetModelConfiguration_RequestTypeSupport{}

type _SetModelConfiguration_RequestTypeSupport struct{}

func (t _SetModelConfiguration_RequestTypeSupport) New() types.Message {
	return NewSetModelConfiguration_Request()
}

func (t _SetModelConfiguration_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SetModelConfiguration_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SetModelConfiguration_Request__create())
}

func (t _SetModelConfiguration_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SetModelConfiguration_Request__destroy((*C.gazebo_msgs__srv__SetModelConfiguration_Request)(pointer_to_free))
}

func (t _SetModelConfiguration_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetModelConfiguration_Request)
	mem := (*C.gazebo_msgs__srv__SetModelConfiguration_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.model_name), m.ModelName)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.urdf_param_name), m.UrdfParamName)
	primitives.String__Sequence_to_C((*primitives.CString__Sequence)(unsafe.Pointer(&mem.joint_names)), m.JointNames)
	primitives.Float64__Sequence_to_C((*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.joint_positions)), m.JointPositions)
}

func (t _SetModelConfiguration_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetModelConfiguration_Request)
	mem := (*C.gazebo_msgs__srv__SetModelConfiguration_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ModelName, unsafe.Pointer(&mem.model_name))
	primitives.StringAsGoStruct(&m.UrdfParamName, unsafe.Pointer(&mem.urdf_param_name))
	primitives.String__Sequence_to_Go(&m.JointNames, *(*primitives.CString__Sequence)(unsafe.Pointer(&mem.joint_names)))
	primitives.Float64__Sequence_to_Go(&m.JointPositions, *(*primitives.CFloat64__Sequence)(unsafe.Pointer(&mem.joint_positions)))
}

func (t _SetModelConfiguration_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SetModelConfiguration_Request())
}

type CSetModelConfiguration_Request = C.gazebo_msgs__srv__SetModelConfiguration_Request
type CSetModelConfiguration_Request__Sequence = C.gazebo_msgs__srv__SetModelConfiguration_Request__Sequence

func SetModelConfiguration_Request__Sequence_to_Go(goSlice *[]SetModelConfiguration_Request, cSlice CSetModelConfiguration_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetModelConfiguration_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SetModelConfiguration_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetModelConfiguration_Request * uintptr(i)),
		))
		SetModelConfiguration_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SetModelConfiguration_Request__Sequence_to_C(cSlice *CSetModelConfiguration_Request__Sequence, goSlice []SetModelConfiguration_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SetModelConfiguration_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SetModelConfiguration_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SetModelConfiguration_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetModelConfiguration_Request * uintptr(i)),
		))
		SetModelConfiguration_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SetModelConfiguration_Request__Array_to_Go(goSlice []SetModelConfiguration_Request, cSlice []CSetModelConfiguration_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetModelConfiguration_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetModelConfiguration_Request__Array_to_C(cSlice []CSetModelConfiguration_Request, goSlice []SetModelConfiguration_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetModelConfiguration_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
