/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	gazebo_msgs_msg "github.com/tiiuae/rclgo-msgs/gazebo_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/set_model_state.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SetModelState_Request", SetModelState_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSetModelState_Request
// function instead.
type SetModelState_Request struct {
	ModelState gazebo_msgs_msg.ModelState `yaml:"model_state"`// Deprecated, kept for ROS 1 bridge.Use SetEntityState
}

// NewSetModelState_Request creates a new SetModelState_Request with default values.
func NewSetModelState_Request() *SetModelState_Request {
	self := SetModelState_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetModelState_Request) Clone() *SetModelState_Request {
	c := &SetModelState_Request{}
	c.ModelState = *t.ModelState.Clone()
	return c
}

func (t *SetModelState_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetModelState_Request) SetDefaults() {
	t.ModelState.SetDefaults()
}

// CloneSetModelState_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetModelState_RequestSlice(dst, src []SetModelState_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetModelState_RequestTypeSupport types.MessageTypeSupport = _SetModelState_RequestTypeSupport{}

type _SetModelState_RequestTypeSupport struct{}

func (t _SetModelState_RequestTypeSupport) New() types.Message {
	return NewSetModelState_Request()
}

func (t _SetModelState_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SetModelState_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SetModelState_Request__create())
}

func (t _SetModelState_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SetModelState_Request__destroy((*C.gazebo_msgs__srv__SetModelState_Request)(pointer_to_free))
}

func (t _SetModelState_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetModelState_Request)
	mem := (*C.gazebo_msgs__srv__SetModelState_Request)(dst)
	gazebo_msgs_msg.ModelStateTypeSupport.AsCStruct(unsafe.Pointer(&mem.model_state), &m.ModelState)
}

func (t _SetModelState_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetModelState_Request)
	mem := (*C.gazebo_msgs__srv__SetModelState_Request)(ros2_message_buffer)
	gazebo_msgs_msg.ModelStateTypeSupport.AsGoStruct(&m.ModelState, unsafe.Pointer(&mem.model_state))
}

func (t _SetModelState_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SetModelState_Request())
}

type CSetModelState_Request = C.gazebo_msgs__srv__SetModelState_Request
type CSetModelState_Request__Sequence = C.gazebo_msgs__srv__SetModelState_Request__Sequence

func SetModelState_Request__Sequence_to_Go(goSlice *[]SetModelState_Request, cSlice CSetModelState_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetModelState_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SetModelState_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetModelState_Request * uintptr(i)),
		))
		SetModelState_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SetModelState_Request__Sequence_to_C(cSlice *CSetModelState_Request__Sequence, goSlice []SetModelState_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SetModelState_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SetModelState_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SetModelState_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetModelState_Request * uintptr(i)),
		))
		SetModelState_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SetModelState_Request__Array_to_Go(goSlice []SetModelState_Request, cSlice []CSetModelState_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetModelState_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetModelState_Request__Array_to_C(cSlice []CSetModelState_Request, goSlice []SetModelState_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetModelState_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
