/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	gazebo_msgs_msg "github.com/tiiuae/rclgo-msgs/gazebo_msgs/msg"
	geometry_msgs_msg "github.com/tiiuae/rclgo-msgs/geometry_msgs/msg"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/set_physics_properties.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SetPhysicsProperties_Request", SetPhysicsProperties_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSetPhysicsProperties_Request
// function instead.
type SetPhysicsProperties_Request struct {
	TimeStep float64 `yaml:"time_step"`// dt in seconds. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	MaxUpdateRate float64 `yaml:"max_update_rate"`// throttle maximum physics update rate. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	Gravity geometry_msgs_msg.Vector3 `yaml:"gravity"`// gravity vector (e.g. earth ~[0,0,-9.81]). sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
	OdeConfig gazebo_msgs_msg.ODEPhysics `yaml:"ode_config"`// configurations for ODE. sets pose and twist of a link.  All children link poses/twists of the URDF tree will be updated accordingly
}

// NewSetPhysicsProperties_Request creates a new SetPhysicsProperties_Request with default values.
func NewSetPhysicsProperties_Request() *SetPhysicsProperties_Request {
	self := SetPhysicsProperties_Request{}
	self.SetDefaults()
	return &self
}

func (t *SetPhysicsProperties_Request) Clone() *SetPhysicsProperties_Request {
	c := &SetPhysicsProperties_Request{}
	c.TimeStep = t.TimeStep
	c.MaxUpdateRate = t.MaxUpdateRate
	c.Gravity = *t.Gravity.Clone()
	c.OdeConfig = *t.OdeConfig.Clone()
	return c
}

func (t *SetPhysicsProperties_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SetPhysicsProperties_Request) SetDefaults() {
	t.TimeStep = 0
	t.MaxUpdateRate = 0
	t.Gravity.SetDefaults()
	t.OdeConfig.SetDefaults()
}

// CloneSetPhysicsProperties_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSetPhysicsProperties_RequestSlice(dst, src []SetPhysicsProperties_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SetPhysicsProperties_RequestTypeSupport types.MessageTypeSupport = _SetPhysicsProperties_RequestTypeSupport{}

type _SetPhysicsProperties_RequestTypeSupport struct{}

func (t _SetPhysicsProperties_RequestTypeSupport) New() types.Message {
	return NewSetPhysicsProperties_Request()
}

func (t _SetPhysicsProperties_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SetPhysicsProperties_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SetPhysicsProperties_Request__create())
}

func (t _SetPhysicsProperties_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SetPhysicsProperties_Request__destroy((*C.gazebo_msgs__srv__SetPhysicsProperties_Request)(pointer_to_free))
}

func (t _SetPhysicsProperties_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SetPhysicsProperties_Request)
	mem := (*C.gazebo_msgs__srv__SetPhysicsProperties_Request)(dst)
	mem.time_step = C.double(m.TimeStep)
	mem.max_update_rate = C.double(m.MaxUpdateRate)
	geometry_msgs_msg.Vector3TypeSupport.AsCStruct(unsafe.Pointer(&mem.gravity), &m.Gravity)
	gazebo_msgs_msg.ODEPhysicsTypeSupport.AsCStruct(unsafe.Pointer(&mem.ode_config), &m.OdeConfig)
}

func (t _SetPhysicsProperties_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SetPhysicsProperties_Request)
	mem := (*C.gazebo_msgs__srv__SetPhysicsProperties_Request)(ros2_message_buffer)
	m.TimeStep = float64(mem.time_step)
	m.MaxUpdateRate = float64(mem.max_update_rate)
	geometry_msgs_msg.Vector3TypeSupport.AsGoStruct(&m.Gravity, unsafe.Pointer(&mem.gravity))
	gazebo_msgs_msg.ODEPhysicsTypeSupport.AsGoStruct(&m.OdeConfig, unsafe.Pointer(&mem.ode_config))
}

func (t _SetPhysicsProperties_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SetPhysicsProperties_Request())
}

type CSetPhysicsProperties_Request = C.gazebo_msgs__srv__SetPhysicsProperties_Request
type CSetPhysicsProperties_Request__Sequence = C.gazebo_msgs__srv__SetPhysicsProperties_Request__Sequence

func SetPhysicsProperties_Request__Sequence_to_Go(goSlice *[]SetPhysicsProperties_Request, cSlice CSetPhysicsProperties_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SetPhysicsProperties_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SetPhysicsProperties_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetPhysicsProperties_Request * uintptr(i)),
		))
		SetPhysicsProperties_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SetPhysicsProperties_Request__Sequence_to_C(cSlice *CSetPhysicsProperties_Request__Sequence, goSlice []SetPhysicsProperties_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SetPhysicsProperties_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SetPhysicsProperties_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SetPhysicsProperties_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SetPhysicsProperties_Request * uintptr(i)),
		))
		SetPhysicsProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SetPhysicsProperties_Request__Array_to_Go(goSlice []SetPhysicsProperties_Request, cSlice []CSetPhysicsProperties_Request) {
	for i := 0; i < len(cSlice); i++ {
		SetPhysicsProperties_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SetPhysicsProperties_Request__Array_to_C(cSlice []CSetPhysicsProperties_Request, goSlice []SetPhysicsProperties_Request) {
	for i := 0; i < len(goSlice); i++ {
		SetPhysicsProperties_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
