/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	geometry_msgs_msg "github.com/tiiuae/rclgo-msgs/geometry_msgs/msg"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c
#cgo LDFLAGS: -lgeometry_msgs__rosidl_typesupport_c -lgeometry_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/spawn_model.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SpawnModel_Request", SpawnModel_RequestTypeSupport)
}

// Do not create instances of this type directly. Always use NewSpawnModel_Request
// function instead.
type SpawnModel_Request struct {
	ModelName string `yaml:"model_name"`// name of the model to be spawn. Deprecated, kept for ROS 1 bridge.Use SpawnEntity
	ModelXml string `yaml:"model_xml"`// this should be an urdf or gazebo xml. Deprecated, kept for ROS 1 bridge.Use SpawnEntity
	RobotNamespace string `yaml:"robot_namespace"`// spawn robot and all ROS interfaces under this namespace. Deprecated, kept for ROS 1 bridge.Use SpawnEntity
	InitialPose geometry_msgs_msg.Pose `yaml:"initial_pose"`// only applied to canonical body. Deprecated, kept for ROS 1 bridge.Use SpawnEntity
	ReferenceFrame string `yaml:"reference_frame"`// initial_pose is defined relative to the frame of this model/body. Deprecated, kept for ROS 1 bridge.Use SpawnEntity
}

// NewSpawnModel_Request creates a new SpawnModel_Request with default values.
func NewSpawnModel_Request() *SpawnModel_Request {
	self := SpawnModel_Request{}
	self.SetDefaults()
	return &self
}

func (t *SpawnModel_Request) Clone() *SpawnModel_Request {
	c := &SpawnModel_Request{}
	c.ModelName = t.ModelName
	c.ModelXml = t.ModelXml
	c.RobotNamespace = t.RobotNamespace
	c.InitialPose = *t.InitialPose.Clone()
	c.ReferenceFrame = t.ReferenceFrame
	return c
}

func (t *SpawnModel_Request) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SpawnModel_Request) SetDefaults() {
	t.ModelName = ""
	t.ModelXml = ""
	t.RobotNamespace = ""
	t.InitialPose.SetDefaults()
	t.ReferenceFrame = ""
}

// CloneSpawnModel_RequestSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSpawnModel_RequestSlice(dst, src []SpawnModel_Request) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SpawnModel_RequestTypeSupport types.MessageTypeSupport = _SpawnModel_RequestTypeSupport{}

type _SpawnModel_RequestTypeSupport struct{}

func (t _SpawnModel_RequestTypeSupport) New() types.Message {
	return NewSpawnModel_Request()
}

func (t _SpawnModel_RequestTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SpawnModel_Request
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SpawnModel_Request__create())
}

func (t _SpawnModel_RequestTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SpawnModel_Request__destroy((*C.gazebo_msgs__srv__SpawnModel_Request)(pointer_to_free))
}

func (t _SpawnModel_RequestTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SpawnModel_Request)
	mem := (*C.gazebo_msgs__srv__SpawnModel_Request)(dst)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.model_name), m.ModelName)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.model_xml), m.ModelXml)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.robot_namespace), m.RobotNamespace)
	geometry_msgs_msg.PoseTypeSupport.AsCStruct(unsafe.Pointer(&mem.initial_pose), &m.InitialPose)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.reference_frame), m.ReferenceFrame)
}

func (t _SpawnModel_RequestTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SpawnModel_Request)
	mem := (*C.gazebo_msgs__srv__SpawnModel_Request)(ros2_message_buffer)
	primitives.StringAsGoStruct(&m.ModelName, unsafe.Pointer(&mem.model_name))
	primitives.StringAsGoStruct(&m.ModelXml, unsafe.Pointer(&mem.model_xml))
	primitives.StringAsGoStruct(&m.RobotNamespace, unsafe.Pointer(&mem.robot_namespace))
	geometry_msgs_msg.PoseTypeSupport.AsGoStruct(&m.InitialPose, unsafe.Pointer(&mem.initial_pose))
	primitives.StringAsGoStruct(&m.ReferenceFrame, unsafe.Pointer(&mem.reference_frame))
}

func (t _SpawnModel_RequestTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SpawnModel_Request())
}

type CSpawnModel_Request = C.gazebo_msgs__srv__SpawnModel_Request
type CSpawnModel_Request__Sequence = C.gazebo_msgs__srv__SpawnModel_Request__Sequence

func SpawnModel_Request__Sequence_to_Go(goSlice *[]SpawnModel_Request, cSlice CSpawnModel_Request__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SpawnModel_Request, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SpawnModel_Request__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Request * uintptr(i)),
		))
		SpawnModel_RequestTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SpawnModel_Request__Sequence_to_C(cSlice *CSpawnModel_Request__Sequence, goSlice []SpawnModel_Request) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SpawnModel_Request)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Request * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SpawnModel_Request)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Request * uintptr(i)),
		))
		SpawnModel_RequestTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SpawnModel_Request__Array_to_Go(goSlice []SpawnModel_Request, cSlice []CSpawnModel_Request) {
	for i := 0; i < len(cSlice); i++ {
		SpawnModel_RequestTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SpawnModel_Request__Array_to_C(cSlice []CSpawnModel_Request, goSlice []SpawnModel_Request) {
	for i := 0; i < len(goSlice); i++ {
		SpawnModel_RequestTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
