/*
This file is part of rclgo

Copyright © 2021 Technology Innovation Institute, United Arab Emirates

Licensed under the Apache License, Version 2.0 (the "License");
	http://www.apache.org/licenses/LICENSE-2.0
*/

/*
THIS FILE IS AUTOGENERATED BY 'rclgo-gen generate'
*/

package gazebo_msgs_srv
import (
	"unsafe"

	"github.com/tiiuae/rclgo/pkg/rclgo/types"
	"github.com/tiiuae/rclgo/pkg/rclgo/typemap"
	primitives "github.com/tiiuae/rclgo/pkg/rclgo/primitives"
	
)
/*
#cgo LDFLAGS: -L/opt/ros/galactic/lib -Wl,-rpath=/opt/ros/galactic/lib -lrcl -lrosidl_runtime_c -lrosidl_typesupport_c -lrcutils -lrmw_implementation
#cgo LDFLAGS: -lgazebo_msgs__rosidl_typesupport_c -lgazebo_msgs__rosidl_generator_c

#cgo CFLAGS: -I/opt/ros/galactic/include

#include <rosidl_runtime_c/message_type_support_struct.h>

#include <gazebo_msgs/srv/spawn_model.h>

*/
import "C"

func init() {
	typemap.RegisterMessage("gazebo_msgs/SpawnModel_Response", SpawnModel_ResponseTypeSupport)
}

// Do not create instances of this type directly. Always use NewSpawnModel_Response
// function instead.
type SpawnModel_Response struct {
	Success bool `yaml:"success"`// return true if spawn successful. Deprecated, kept for ROS 1 bridge.Use SpawnEntityif left empty or "world", then gazebo world frame is usedif non-existent model/body is specified, an error is returnedand the model is not spawned
	StatusMessage string `yaml:"status_message"`// comments if available. Deprecated, kept for ROS 1 bridge.Use SpawnEntityif left empty or "world", then gazebo world frame is usedif non-existent model/body is specified, an error is returnedand the model is not spawned
}

// NewSpawnModel_Response creates a new SpawnModel_Response with default values.
func NewSpawnModel_Response() *SpawnModel_Response {
	self := SpawnModel_Response{}
	self.SetDefaults()
	return &self
}

func (t *SpawnModel_Response) Clone() *SpawnModel_Response {
	c := &SpawnModel_Response{}
	c.Success = t.Success
	c.StatusMessage = t.StatusMessage
	return c
}

func (t *SpawnModel_Response) CloneMsg() types.Message {
	return t.Clone()
}

func (t *SpawnModel_Response) SetDefaults() {
	t.Success = false
	t.StatusMessage = ""
}

// CloneSpawnModel_ResponseSlice clones src to dst by calling Clone for each element in
// src. Panics if len(dst) < len(src).
func CloneSpawnModel_ResponseSlice(dst, src []SpawnModel_Response) {
	for i := range src {
		dst[i] = *src[i].Clone()
	}
}

// Modifying this variable is undefined behavior.
var SpawnModel_ResponseTypeSupport types.MessageTypeSupport = _SpawnModel_ResponseTypeSupport{}

type _SpawnModel_ResponseTypeSupport struct{}

func (t _SpawnModel_ResponseTypeSupport) New() types.Message {
	return NewSpawnModel_Response()
}

func (t _SpawnModel_ResponseTypeSupport) PrepareMemory() unsafe.Pointer { //returns *C.gazebo_msgs__srv__SpawnModel_Response
	return (unsafe.Pointer)(C.gazebo_msgs__srv__SpawnModel_Response__create())
}

func (t _SpawnModel_ResponseTypeSupport) ReleaseMemory(pointer_to_free unsafe.Pointer) {
	C.gazebo_msgs__srv__SpawnModel_Response__destroy((*C.gazebo_msgs__srv__SpawnModel_Response)(pointer_to_free))
}

func (t _SpawnModel_ResponseTypeSupport) AsCStruct(dst unsafe.Pointer, msg types.Message) {
	m := msg.(*SpawnModel_Response)
	mem := (*C.gazebo_msgs__srv__SpawnModel_Response)(dst)
	mem.success = C.bool(m.Success)
	primitives.StringAsCStruct(unsafe.Pointer(&mem.status_message), m.StatusMessage)
}

func (t _SpawnModel_ResponseTypeSupport) AsGoStruct(msg types.Message, ros2_message_buffer unsafe.Pointer) {
	m := msg.(*SpawnModel_Response)
	mem := (*C.gazebo_msgs__srv__SpawnModel_Response)(ros2_message_buffer)
	m.Success = bool(mem.success)
	primitives.StringAsGoStruct(&m.StatusMessage, unsafe.Pointer(&mem.status_message))
}

func (t _SpawnModel_ResponseTypeSupport) TypeSupport() unsafe.Pointer {
	return unsafe.Pointer(C.rosidl_typesupport_c__get_message_type_support_handle__gazebo_msgs__srv__SpawnModel_Response())
}

type CSpawnModel_Response = C.gazebo_msgs__srv__SpawnModel_Response
type CSpawnModel_Response__Sequence = C.gazebo_msgs__srv__SpawnModel_Response__Sequence

func SpawnModel_Response__Sequence_to_Go(goSlice *[]SpawnModel_Response, cSlice CSpawnModel_Response__Sequence) {
	if cSlice.size == 0 {
		return
	}
	*goSlice = make([]SpawnModel_Response, int64(cSlice.size))
	for i := 0; i < int(cSlice.size); i++ {
		cIdx := (*C.gazebo_msgs__srv__SpawnModel_Response__Sequence)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Response * uintptr(i)),
		))
		SpawnModel_ResponseTypeSupport.AsGoStruct(&(*goSlice)[i], unsafe.Pointer(cIdx))
	}
}
func SpawnModel_Response__Sequence_to_C(cSlice *CSpawnModel_Response__Sequence, goSlice []SpawnModel_Response) {
	if len(goSlice) == 0 {
		return
	}
	cSlice.data = (*C.gazebo_msgs__srv__SpawnModel_Response)(C.malloc((C.size_t)(C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Response * uintptr(len(goSlice)))))
	cSlice.capacity = C.size_t(len(goSlice))
	cSlice.size = cSlice.capacity

	for i, v := range goSlice {
		cIdx := (*C.gazebo_msgs__srv__SpawnModel_Response)(unsafe.Pointer(
			uintptr(unsafe.Pointer(cSlice.data)) + (C.sizeof_struct_gazebo_msgs__srv__SpawnModel_Response * uintptr(i)),
		))
		SpawnModel_ResponseTypeSupport.AsCStruct(unsafe.Pointer(cIdx), &v)
	}
}
func SpawnModel_Response__Array_to_Go(goSlice []SpawnModel_Response, cSlice []CSpawnModel_Response) {
	for i := 0; i < len(cSlice); i++ {
		SpawnModel_ResponseTypeSupport.AsGoStruct(&goSlice[i], unsafe.Pointer(&cSlice[i]))
	}
}
func SpawnModel_Response__Array_to_C(cSlice []CSpawnModel_Response, goSlice []SpawnModel_Response) {
	for i := 0; i < len(goSlice); i++ {
		SpawnModel_ResponseTypeSupport.AsCStruct(unsafe.Pointer(&cSlice[i]), &goSlice[i])
	}
}
